- src/Magento/FunctionalTestingFramework/Test/Objects/ActionGroupObject.php
- added [ and ] to regex in actionGroupObject.
1. magento/magento2-functional-testing-framework#693: [ActionGroup] Characters "[" and "]" must be allowed in selector/url parameters
> MQE-693: Characters "[" and "]" must be allowed in selector/url parameters

- dev/tests/verification/Resources/AssertTest.txt
- dev/tests/verification/TestModule/Test/AssertTest.xml
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
- src/Magento/FunctionalTestingFramework/Test/Util/ActionMergeUtil.php
- src/Magento/FunctionalTestingFramework/Test/etc/testSchema.xsd
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
Schema now uses the nested assertion action syntax. Old syntax (single line) is still supported, but documentation has been changed to point users to use the new syntax.
1. magento/magento2-functional-testing-framework#MQE-559: Use more descriptive assertion syntax
> MQE-559: Use more descriptive assertion syntax

- src/Magento/FunctionalTestingFramework/Test/etc/Actions/assertActions.xsd
- src/Magento/FunctionalTestingFramework/Test/etc/Actions/clickActions.xsd
- src/Magento/FunctionalTestingFramework/Test/etc/Actions/commonAttributes.xsd
- src/Magento/FunctionalTestingFramework/Test/etc/Actions/customActions.xsd
- src/Magento/FunctionalTestingFramework/Test/etc/Actions/dataActions.xsd
- src/Magento/FunctionalTestingFramework/Test/etc/Actions/dontSeeActions.xsd
- src/Magento/FunctionalTestingFramework/Test/etc/Actions/grabActions.xsd
- src/Magento/FunctionalTestingFramework/Test/etc/Actions/seeActions.xsd
- src/Magento/FunctionalTestingFramework/Test/etc/Actions/switchToActions.xsd
- src/Magento/FunctionalTestingFramework/Test/etc/Actions/waitActions.xsd
- src/Magento/FunctionalTestingFramework/Test/etc/actionGroupSchema.xsd
- src/Magento/FunctionalTestingFramework/Test/etc/actionTypeTags.xsd
- src/Magento/FunctionalTestingFramework/Test/etc/testSchema.xsd
Updated XML Schemas to be compatible with XSD Diagram parsing tool
> Updated XML Schemas to be compatible with XSD Diagram parsing tool

- etc/di.xml
di.xml didn't have configuration for node path `<test><before|after><actionGroup><argument>`, which was causing the failure.
1. magento/magento2-functional-testing-framework#<732>: Unable to call action group with arguments in "after" block
> MQE-732: Unable to call action group with arguments in "after" block

- dev/tests/verification/Resources/PageReplacementTest.txt
- dev/tests/verification/TestModule/Page/SamplePage.xml
- dev/tests/verification/TestModule/Test/PageReplacementTest.xml
- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/DataObjectHandler.php
- src/Magento/FunctionalTestingFramework/Page/Objects/PageObject.php
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
{{_ENV.value}} references are no longer done on generation; they are done in test runtime. This fixes the issue of Magento instances changing .env contents post generation in builds.
1. magento/magento2-functional-testing-framework#<685>: References to ENV file must be done at test run-time
> MQE-685: References to ENV file must be done at test run-time

- dev/tests/verification/TestModule/Test/XmlDuplicateTest.xml
- dev/tests/verification/TestModuleMerged/Test/MergeXmlDuplicateTest.xml
- dev/tests/verification/Tests/XmlDuplicateGenerationTest.php
- etc/di.xml
di.xml fixes to make sure hooks have all data actions, as well as overall review of di.xml configurationf or other missing actions.
1. magento/magento2-functional-testing-framework#<740>: Duplicates in test hook cause errors when merging
> MQE-740: Duplicates in test hook cause errors when merging

- dev/tests/unit/Util/OperationDefinitionBuilder.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/OperationDefinitionObjectHandler.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Objects/OperationDefinitionObject.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Persist/Curl/AdminExecutor.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Persist/CurlHandler.php
- src/Magento/FunctionalTestingFramework/DataGenerator/etc/dataOperation.xsd
- added `removeBackend` attribute that removes addition of MAGENTO_BACKEND_NAME to metadata of type `adminFormKey`
1. magento/magento2-functional-testing-framework#820: MSI form posts use a single "/admin/" vs "/admin/admin/" URLs used in other areas of the Admin.
> MQE-820: MSI form posts use a single "/admin/" vs "/admin/admin/" URLs used in other areas of the Admin.

- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
- src/Magento/FunctionalTestingFramework/Test/etc/Actions/assertActions.xsd
- Changed schema to allow for above
- Added validation in lieu of xsd validation.
1. magento/magento2-functional-testing-framework#837: Assert sub-elements can't be declared out of sequence
>  MQE-837: Assert sub-elements can't be declared out of sequence

- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
- src/Magento/FunctionalTestingFramework/Util/ConfigSanitizerUtil.php
- src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
Using --force flag now allows users to generate tests regardless if their .env has MAGENTO_BASE_URL defined, or defined as ''.
1. magento/magento2-functional-testing-framework#841: robo generate:tests --force should not require MAGENTO_BASE_URL
> MQE-841: robo generate:tests --force should not require MAGENTO_BASE_URL

- dev/tests/verification/Resources/ActionGroupWithDataOverrideTest.txt
- dev/tests/verification/Resources/ActionGroupWithDataTest.txt
- dev/tests/verification/Resources/ActionGroupWithNoDefaultTest.txt
- dev/tests/verification/Resources/ActionGroupWithPersistedData.txt
- dev/tests/verification/Resources/ActionGroupWithTopLevelPersistedData.txt
- dev/tests/verification/Resources/ArgumentWithSameNameAsElement.txt
- dev/tests/verification/Resources/BasicActionGroupTest.txt
- dev/tests/verification/Resources/BasicFunctionalTest.txt
- dev/tests/verification/Resources/BasicMergeTest.txt
- dev/tests/verification/Resources/MergedActionGroupTest.txt
- dev/tests/verification/Resources/MergedReferencesTest.txt
- dev/tests/verification/Resources/MultipleActionGroupsTest.txt
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
- Stories/Features now generate at function level, not class level.
1. magento/magento2-functional-testing-framework#842: Update feature and story tags to map to test functions when generated
> MQE-842: Update feature and story tags to map to test functions when generated

- src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
- removed trailing space from $versionUrl
1. magento/magento2-functional-testing-framework#852: Incorrect  Magento Version URL
> MQE-852: Incorrect Magento Version URL

- .env.example
- RoboFile.php
- bin/mftf
- bootstrap.php
- src/Magento/FunctionalTestingFramework/Console/BuildProjectCommand.php
- src/Magento/FunctionalTestingFramework/Console/SetupEnvCommand.php
- src/Magento/FunctionalTestingFramework/Util/Env/EnvProcessor.php
Introduced `bin/mftf` CLI tool for easy management of console commands. 
- added `bin/mftf setup:env` command which allows generating `.env` file by specified parameters;
- added `bin/mftf build:project` which generates configuration files for the project and generates the Codeception project. More efficient replacement for `vendor/bin/robo build:project`.
1. magento/magento2-functional-testing-framework#60: Build interactive configuration tool for populating .env properties
> magento/magento2-functional-testing-framework#60: Build interactive configuration tool for populating .env properties

- RoboFile.php
Exception throwing has been added to test generation method in order to check if `vendor/bin/robo build:project` has been ran and .env configuration file has been filled in.
1. magento/magento2-functional-testing-framework#61: Validate build:project was run before attempting to generate tests
> magento/magento2-functional-testing-framework#61: Validate build:project was run before attempting to generate tests

- dev/tests/verification/Tests/SuiteGenerationTest.php
- src/Magento/FunctionalTestingFramework/Suite/SuiteGenerator.php
- src/Magento/FunctionalTestingFramework/Suite/Util/SuiteObjectExtractor.php
- src/Magento/FunctionalTestingFramework/Util/Filesystem/DirSetupUtil.php
- src/Magento/FunctionalTestingFramework/Util/Manifest/DefaultTestManifest.php
- src/Magento/FunctionalTestingFramework/Util/Manifest/SingleRunTestManifest.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
- add new generate all method to SuiteGenerator
- modify TestManifest to only clear once
- introduce argument to exclude tests during generation
2. ...
> MQE-778: robo generate:tests generates all tests and suites by default

- dev/tests/_bootstrap.php
- src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
- MFTF and MFTF Tests can now interact with one another properly even if installed via composer. Pathing and anchoring is now done via composer autoload file checking.
- ModuleResolver now correctly refers to MAGENTO_BP instead of relative pathing.
1. magento/magento2-functional-testing-framework#768: Framework cannot depend on relative file structure to execute tests
> MQE-768: Framework cannot depend on relative file structure to execute tests

- dev/tests/verification/Resources/BasicFunctionalTest.txt
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
- executeJS now assigns a variable for storage.
1. magento/magento2-functional-testing-framework#818: Enable executeJS to save a variable
> MQE-818: Enable executeJS to save a variable

- src/Magento/FunctionalTestingFramework/Suite/Util/SuiteObjectExtractor.php
- src/Magento/FunctionalTestingFramework/Test/Objects/TestObject.php
During generation, for the specified test set, if there is a conflict between a suite name and a group name, generation fails. An error is printed with the suite and test details of the conflict
N/A
> MQE-782: Fatal error is thrown when a group name conflicts with an existing suite name

- etc/di.xml
- src/Magento/FunctionalTestingFramework/Config/FileResolver/Module.php
- src/Magento/FunctionalTestingFramework/Config/FileResolver/Root.php
- alter Root based file resolver to extend module fileresolver
- refactor Module based fileresolver to expose utility method
2. ...
> MQE-784: Update parser to read suites in from extensions

- bin/static-checks
- bin/static-checks.bat
- dev/tests/unit/Magento/FunctionalTestFramework/Util/Sorter/ParallelGroupSorterTest.php
- src/Magento/FunctionalTestingFramework/Suite/Handlers/SuiteObjectHandler.php
- src/Magento/FunctionalTestingFramework/Suite/SuiteGenerator.php
- src/Magento/FunctionalTestingFramework/Util/Manifest/BaseTestManifest.php
- src/Magento/FunctionalTestingFramework/Util/Manifest/DefaultTestManifest.php
- src/Magento/FunctionalTestingFramework/Util/Manifest/ParallelTestManifest.php
- src/Magento/FunctionalTestingFramework/Util/Manifest/SingleRunTestManifest.php
- src/Magento/FunctionalTestingFramework/Util/Manifest/TestManifestFactory.php
- src/Magento/FunctionalTestingFramework/Util/Sorter/ParallelGroupSorter.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
> MQE-893: Add flag to robo generate: tests which accepts a specific set of tests to execute

- dev/tests/unit/Magento/FunctionalTestFramework/Test/Config/ActionGroupDomTest.php
- dev/tests/verification/TestModule/ActionGroup/XmlDuplicateActionGroup.xml
- etc/di.xml
- src/Magento/FunctionalTestingFramework/Exceptions/Collector/ExceptionCollector.php
- src/Magento/FunctionalTestingFramework/Test/Config/ActionGroupDom.php
- src/Magento/FunctionalTestingFramework/Test/Config/Dom.php
- src/Magento/FunctionalTestingFramework/Test/Config/Reader/Filesystem.php
- src/Magento/FunctionalTestingFramework/Test/Util/ActionGroupObjectExtractor.php
- src/Magento/FunctionalTestingFramework/Test/etc/actionGroupSchema.xsd
> MQE-790: Error for duplicate step keys in a single action group definition

- RoboFile.php
- dev/tests/_bootstrap.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/ActionObjectExtractorTest.php
- src/Magento/FunctionalTestingFramework/Config/MftfApplicationConfig.php
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
- src/Magento/FunctionalTestingFramework/Test/Util/ActionObjectExtractor.php
- src/Magento/FunctionalTestingFramework/Test/Util/TestObjectExtractor.php
- src/Magento/FunctionalTestingFramework/Util/ConfigSanitizerUtil.php
- src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
> MQE-809: Throw a warning or error when step key referencing in merges is invalid or ambiguous

- dev/tests/verification/Resources/ActionGroupWithPassedArgumentAndStringSelectorParam.txt
- dev/tests/verification/Resources/ActionGroupWithSingleParameterSelectorFromPassedArgument.txt
- dev/tests/verification/Resources/DataReplacementTest.txt
- dev/tests/verification/Resources/ParameterArrayTest.txt
- dev/tests/verification/Resources/SectionReplacementTest.txt
- dev/tests/verification/TestModule/Test/DataReplacementTest.xml
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
- Fixed above bug on uniqueness references
- Refactor addUniquenessFunctionCall in testGenerator to be more conscise
> MQE-914: Multiple Uniqueness References On Same Entity Generates Incorrectly

- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
- Fixed exception message for conditionalClick
> MQE-699:  Exception message for "conditionalClick" failure uses '$selector' instead of '$dependentSelector'.

- dev/tests/unit/Magento/FunctionalTestFramework/Test/Objects/ActionObjectTest.php
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
Added support for passing array entities as arguments.
As a Test Engineer I want to pass data entity arrays as arguments so that I can not have to use hard-coded flat arrays.
For example:
**The Entity**
```xml
<entities>
<entity name="DefaultCustomerGroup" type="customerGroup">
<array key="group_names">
<item>Default</item>
</array>
</entity>
</entities>
```
**The ActionGroup**
```xml
<actionGroups>
<actionGroup name="searchAndMultiSelectActionGroup">
<arguments>
<argument name="options" />
</arguments>
<selectMultipleOptions filterSelector="foo" optionSelector="bar" stepKey="selectSpecifiedOptions">
<array>{{options}}</array>
</selectMultipleOptions>
</actionGroup>
</actionGroups>
```
**The Test**
```xml
<tests>
<test name="AdminCreateCustomerTest">
<actionGroup …
```
> Add ability to use array entities as arguments.

- src/Magento/FunctionalTestingFramework/Extension/ErrorLogger.php
- src/Magento/FunctionalTestingFramework/Extension/TestContextExtension.php
- Added ErrorLogger object, called after steps in the ContextListener
> MQE-501: JavaScript reporting during test run

- dev/tests/verification/Resources/BasicFunctionalTest.txt
- dev/tests/verification/TestModule/Test/BasicFunctionalTest.xml
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
- Fixed quote issue in waitForElementChanged. Also included fix for performOn, as it's the only other codeception function that takes a closure as an argument.
1. magento/magento2-functional-testing-framework#<899>: Excessive double quotes are being generated in WaitForElementChange method arguments
> MQE-899: Excessive double quotes are being generated in WaitForElementChange method arguments

- src/Magento/FunctionalTestingFramework/Allure/Adapter/MagentoAllureAdapter.php
- src/Magento/FunctionalTestingFramework/Suite/views/SuiteClass.mustache
- src/Magento/FunctionalTestingFramework/Suite/views/partials/testActions.mustache
- src/Magento/FunctionalTestingFramework/Test/Objects/TestObject.php
> MQE-957: MFTF Changes to support DEVOPS-2029

- src/Magento/FunctionalTestingFramework/Util/Sorter/ParallelGroupSorter.php
- array_diff to array_diff_key in ParallelGroupSorter.
1. magento/magento2-functional-testing-framework#970: Tests in Suites being omitted when line counts are exact match
> MQE-970: Tests in Suites being omitted when line counts are exact match

- src/Magento/FunctionalTestingFramework/Suite/Generators/GroupClassGenerator.php
- Changed conditional for actions to use TestGenerator to be based on "createDataKey" existance.
1. magento/magento2-functional-testing-framework#971: DeleteData using url is generated incorrectly in Suite hooks
> MQE-971: DeleteData using url is generated incorrectly in Suite hooks

- CHANGELOG.md
- Added changelog additions for 2.2.0.
> MQE-925: 2.2.0 CHANGELOG

- src/Magento/FunctionalTestingFramework/Extension/ErrorLogger.php
- update logger to validate param existence before using "source" param
2. ...
> MQE-977: ErrorLogger expects source to be a log paramater

- dev/tests/unit/Magento/FunctionalTestFramework/Suite/SuiteGeneratorTest.php
- src/Magento/FunctionalTestingFramework/Suite/SuiteGenerator.php
> MQE-978: Create Test Coverage Around SuiteGenerator Class

- dev/tests/verification/Resources/ActionGroupContainsStepKeyInArgText.txt
- dev/tests/verification/TestModule/ActionGroup/BasicActionGroup.xml
- dev/tests/verification/TestModule/Test/ActionGroupTest.xml
- dev/tests/verification/Tests/ActionGroupGenerationTest.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
…Incorrectly
- fixed issue with stepKey matching argument value replacement
2. ...
> MQE-1011: Keyword Comment In User Input For Action Group Substitutes Incorrectly

- composer.json
- composer.lock
- dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Objects/EntityDataObjectTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Persist/OperationDataArrayResolverTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Suite/SuiteGeneratorTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Objects/ActionGroupObjectTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Objects/ActionObjectTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/ActionMergeUtilTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/ActionObjectExtractorTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/ObjectExtensionUtilTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Util/ModuleResolverTest.php
- dev/tests/unit/Util/TestLoggingUtil.php
- dev/tests/verification/Tests/SuiteGenerationTest.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Objects/EntityDataObject.php
- src/Magento/FunctionalTestingFramework/Exceptions/TestReferenceException.php
- src/Magento/FunctionalTestingFramework/Exceptions/XmlException.php
- src/Magento/FunctionalTestingFramework/Suite/SuiteGenerator.php
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
- src/Magento/FunctionalTestingFramework/Test/Util/ActionObjectExtractor.php
- src/Magento/FunctionalTestingFramework/Test/Util/ObjectExtensionUtil.php
- src/Magento/FunctionalTestingFramework/Util/Logger/LoggingUtil.php
- src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
- add LogginUtil and monolog
- remove expliclit echo/print statements
- update tests
- update mftf exceptions to include log statments
2. ...
> MQE-999: Replace all explicit print or echo statements with logging

- dev/tests/unit/Magento/FunctionalTestFramework/Util/Sorter/ParallelGroupSorterTest.php
- src/Magento/FunctionalTestingFramework/Console/GenerateTestsCommand.php
- src/Magento/FunctionalTestingFramework/Test/Objects/TestObject.php
- src/Magento/FunctionalTestingFramework/Util/Env/EnvProcessor.php
- src/Magento/FunctionalTestingFramework/Util/Manifest/ParallelTestManifest.php
- src/Magento/FunctionalTestingFramework/Util/Sorter/ParallelGroupSorter.php
> MQE-1024: Refactor Algorithm For Mftf Build Groups

- .gitignore
- bin/all-checks.bat
- bin/copyright-check.bat
- bin/static-checks.bat
- dev/tests/unit/Magento/FunctionalTestFramework/Config/Reader/FilesystemTest.php
- src/Magento/FunctionalTestingFramework/Config/Reader/Filesystem.php
- src/Magento/FunctionalTestingFramework/Config/Reader/MftfFilesystem.php
Empty XML files will no longer prevent tests from generating. An error will be logged in these cases.
2. ...
> MQE-1031: Empty files are flagged during generation or dealt with gracefully

- .gitignore
- dev/tests/verification/Resources/ActionGroupWithDataOverrideTest.txt
- dev/tests/verification/Resources/ActionGroupWithDataTest.txt
- dev/tests/verification/Resources/ActionGroupWithNoDefaultTest.txt
- dev/tests/verification/Resources/ActionGroupWithPersistedData.txt
- dev/tests/verification/Resources/ActionGroupWithTopLevelPersistedData.txt
- dev/tests/verification/Resources/ArgumentWithSameNameAsElement.txt
- dev/tests/verification/Resources/BasicActionGroupTest.txt
- dev/tests/verification/Resources/BasicMergeTest.txt
- dev/tests/verification/Resources/ChildExtendedTestAddHooks.txt
- dev/tests/verification/Resources/ChildExtendedTestMerging.txt
- dev/tests/verification/Resources/ChildExtendedTestNoParent.txt
- dev/tests/verification/Resources/ChildExtendedTestRemoveAction.txt
- dev/tests/verification/Resources/ChildExtendedTestRemoveHookAction.txt
- dev/tests/verification/Resources/ChildExtendedTestReplace.txt
- dev/tests/verification/Resources/ChildExtendedTestReplaceHook.txt
- dev/tests/verification/Resources/MergedActionGroupTest.txt
- dev/tests/verification/Resources/MergedReferencesTest.txt
- dev/tests/verification/Resources/MultipleActionGroupsTest.txt
- dev/tests/verification/Resources/ParentExtendedTest.txt
- dev/tests/verification/TestModule/Test/ActionGroupFunctionalTest.xml
- dev/tests/verification/TestModule/Test/ExtendedFunctionalTest.xml
- dev/tests/verification/TestModule/Test/MergeFunctionalTest.xml
- src/Magento/FunctionalTestingFramework/Test/Handlers/TestObjectHandler.php
- src/Magento/FunctionalTestingFramework/Test/Util/AnnotationExtractor.php
- src/Magento/FunctionalTestingFramework/Test/Util/TestObjectExtractor.php
- Added validation of Story/Title combinations for uniqueness
> MQE-1027: Allure report requires a unique story/title for proper reporting

- dev/tests/unit/Magento/FunctionalTestFramework/Util/ModuleResolverTest.php
- src/Magento/FunctionalTestingFramework/Exceptions/TestFrameworkException.php
- src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
- the flag `--force` now completely ignores magento modules when generating.
> MQE-1043: MFTF force flag should ignore the magento base url even when valid

- dev/tests/verification/Resources/DataReplacementTest.txt
- dev/tests/verification/TestModule/Test/DataReplacementTest.xml
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
- added `command` to replacement enabled attributes
> MQE-1016: Variable Substitution Does Not Work For Command Attribute In MagentoCLI Action

- src/Magento/FunctionalTestingFramework/Config/Dom/ArrayNodeConfig.php
- src/Magento/FunctionalTestingFramework/Console/GenerateTestsCommand.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/DataObjectHandler.php
- add logic to flatten assoc array and wrap suite generation in conditional logic
2. ...
> MQE-1059: When a single test is specified all suites should not generate

- dev/tests/_bootstrap.php
- dev/tests/util/MftfTestCase.php
- dev/tests/verification/TestModule/Test/PageReplacementTest.xml
- dev/tests/verification/Tests/SchemaValidationTest.php
- src/Magento/FunctionalTestingFramework/Config/MftfApplicationConfig.php
- src/Magento/FunctionalTestingFramework/Config/Reader/Filesystem.php
- src/Magento/FunctionalTestingFramework/Config/Reader/MftfFilesystem.php
- src/Magento/FunctionalTestingFramework/Console/GenerateTestsCommand.php
When generate:tests is run with --debug information will be given as to what file these type of issues are occurring in.
> MQE-1017: Better Error Messaging When Non-Whitespace Characters Are Outside XML Elements

- dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/ActionGroupObjectExtractorTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/ActionObjectExtractorTest.php
- src/Magento/FunctionalTestingFramework/Test/Util/ActionGroupObjectExtractor.php
- src/Magento/FunctionalTestingFramework/Test/Util/ActionObjectExtractor.php
Actions with empty stepKeyswill now throw errors during generation instead of runtime.
> MQE-1021: Empty Action StepKey Attribute Issues

- dev/tests/functional/_bootstrap.php
- dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Handlers/CredentialStoreTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/ActionObjectExtractorTest.php
- dev/tests/unit/Util/TestLoggingUtil.php
- dev/tests/verification/Resources/PersistedReplacementTest.txt
- src/Magento/FunctionalTestingFramework/Config/Reader/MftfFilesystem.php
- src/Magento/FunctionalTestingFramework/Console/RunTestCommand.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/CredentialStore.php
- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
- src/Magento/FunctionalTestingFramework/Test/Objects/TestObject.php
- src/Magento/FunctionalTestingFramework/Test/Util/ActionMergeUtil.php
- src/Magento/FunctionalTestingFramework/Test/Util/ActionObjectExtractor.php
- src/Magento/FunctionalTestingFramework/Test/etc/actionTypeTags.xsd
- src/Magento/FunctionalTestingFramework/Util/Iterator/File.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
> MQE-1070: Hide Sensitive Creds in Allure Report

- dev/tests/verification/Resources/SectionReplacementTest.txt
- dev/tests/verification/TestModule/Test/SectionReplacementTest.xml
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
- Added negative lookahead for regex.
> MQE-1037: Passing Multiple Element References In Selector Parameters Does Not Generate Correctly When Multiple Elements Are Parameterized

- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
- apiURL now tries to trim index.php/ if present
> MQE-1047: magentoCLI command does not work if MAGENTO_BASE_URL uses index.php

- dev/tests/_bootstrap.php
- dev/tests/functional/_bootstrap.php
- src/Magento/FunctionalTestingFramework/Console/RunTestCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestGroupCommand.php
- src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
- src/Magento/FunctionalTestingFramework/_bootstrap.php
- Overall bootstrap calls standalone bootstrap if instalation is detected to be standalone
> MQE-1110: MFTF run:group does not work with a standalone configuration

- src/Magento/FunctionalTestingFramework/Console/GenerateDevUrnCommand.php
- Added --force flag if user does not have a misc.xml file.
> MQE-917: Eliminate usage of XSD relative paths

- src/Magento/FunctionalTestingFramework/Extension/PageReadinessExtension.php
- src/Magento/FunctionalTestingFramework/Extension/ReadinessMetrics/AbstractMetricCheck.php
- Commented out all logging lines in Readiness Extension so it can be fixed in followup PR.
> MQE-1147: Turn Off Readiness Logging

- dev/tests/verification/Resources/ExtendingSkippedTest.txt
- dev/tests/verification/Resources/SkippedTestWithHooks.txt
- dev/tests/verification/TestModule/Test/ExtendedFunctionalTest.xml
- dev/tests/verification/TestModule/Test/SkippedTest.xml
- dev/tests/verification/Tests/ExtendedGenerationTest.php
- dev/tests/verification/Tests/SkippedGenerationTest.php
- src/Magento/FunctionalTestingFramework/Test/Objects/TestObject.php
- src/Magento/FunctionalTestingFramework/Test/Util/ObjectExtensionUtil.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
This change will allow before and after hooks to be generated for an extended test when those hoooks live on the parent test and that parent test is skipped.
> MQE-1151: Extending a skipped test fails to generate the parent before and after actions

- dev/tests/verification/Resources/ExecuteJsEscapingTest.txt
- dev/tests/verification/TestModule/Test/ExecuteJsTest.xml
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
ExecuteJS should now properly escape sequences without involving persisted data
> MQE-1153: ExecuteJS javascript escaping matches persisted data

- CHANGELOG.md
- bin/mftf
- composer.json
- composer.lock
- etc/config/codeception.dist.yml
- Disabled PageReadinessExtension from defaults
- Updated MFTF version and changelog to reflect patch necessity
> MQE-1216: Disable Readiness Check in default Config

- etc/config/command.php
Remove assumption that `PHP_BINARY` will always be acceptable.
`command.php` assumes that if `PHP_BINARY` is set that it is always the PHP cli bin. When FPM is used, the bin will be `php-fpm` which isn't compatible with the PHP cli. This PR removes that constant and instead uses the already present `PHP_BINDIR` usage
1. magento/magento2-functional-testing-framework#216: command.php assumes that PHP_BINARY is always the PHP cli binary
> Support PHP-FPM in command.php

- src/Magento/FunctionalTestingFramework/Console/BaseGenerateCommand.php
- src/Magento/FunctionalTestingFramework/Console/GenerateSuiteCommand.php
- src/Magento/FunctionalTestingFramework/Console/GenerateTestsCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestGroupCommand.php
> MQE-1009: Generated Suites Are Not Cleaned Up When Regenerating

- dev/tests/_bootstrap.php
- dev/tests/functional/_bootstrap.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Objects/ActionObjectTest.php
- dev/tests/verification/Resources/BasicFunctionalTest.txt
- dev/tests/verification/TestModule/Test/BasicFunctionalTest.xml
- etc/config/.env.example
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
- src/Magento/FunctionalTestingFramework/_bootstrap.php
- new .env DEFAULT_TIMEZONE, defaults to 'America/Los_Angeles'
- generateDate now uses this value (or override if provided)
- DEFAULT_TIMEZONE and timezone attribute are now checked in generation; fast fail in generation as opposed to run-time
- test updates for the above
> MQE-1248: Expose MFTF DEFAULT_TIMEZONE configuration in .env

- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
- Added default value for $timeout attribute (causing issues with CE tests)
> MQE-1142: Use timeout value when waitForLoadingMaskToDisappear

- src/Magento/FunctionalTestingFramework/Extension/ErrorLogger.php
- Added check to ascertain browser is among the available log types
Prevents a call to getLog for a type of log that may not exist
> MQE-1254: MFTF with Firefox fails due to getLog call

- dev/tests/functional/standalone_bootstrap.php
- src/Magento/FunctionalTestingFramework/_bootstrap.php
- Corrected original ticket
- Changed functional run location from alternate Magento Directory to project directory whether standalone or in vendor
> MQE-1040: MFTF standalone commands do not pass down constants correctly

- dev/tests/verification/Resources/ActionGroupWithParameterizedElementWithHyphen.txt
- dev/tests/verification/TestModule/ActionGroup/FunctionalActionGroup.xml
- dev/tests/verification/TestModule/Test/ActionGroupTest.xml
- dev/tests/verification/Tests/ActionGroupGenerationTest.php
- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionGroupObject.php
- Made regex more flexible, should accept any character except for ones that break the pattern.
> MQE-1150: Test generation fails for arguments containing hyphen character

- dev/tests/unit/Magento/FunctionalTestFramework/Util/Validation/DuplicateNodeValidationUtilTest.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Config/Dom.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Config/OperationDom.php
- src/Magento/FunctionalTestingFramework/Page/Config/Dom.php
- src/Magento/FunctionalTestingFramework/Page/Config/SectionDom.php
- src/Magento/FunctionalTestingFramework/Test/Config/ActionGroupDom.php
- src/Magento/FunctionalTestingFramework/Test/Config/Dom.php
- src/Magento/FunctionalTestingFramework/Util/Validation/DuplicateNodeValidationUtil.php
- Parent element is now included in exception output for duplicated child nodes.
> MQE-1148: Include Parent In Output Of Duplicate StepKey or Section Element

- dev/tests/unit/Magento/FunctionalTestFramework/Util/ActionMergeUtilTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Util/TestGeneratorTest.php
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
- src/Magento/FunctionalTestingFramework/Test/Util/ActionMergeUtil.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
Give better error messaging when parsing and referencing steps.
Return error message with test regardless of type of exception
> MQE-1173: [Dev experience] Error on test generation without reference on file

- dev/tests/verification/Resources/ActionGroupWithSectionAndDataAsArguments.txt
- dev/tests/verification/TestModule/ActionGroup/BasicActionGroup.xml
- dev/tests/verification/TestModule/Test/ActionGroupTest.xml
- dev/tests/verification/Tests/ActionGroupGenerationTest.php
- src/Magento/FunctionalTestingFramework/Test/Objects/ArgumentObject.php
- Added support for passing in data into arguments as `{{mydata.value}}`, solves use case where an actionGroup with the following:
-- Argument name=`data` type=`string`
-- Argument name=`section`
-- Action with `selector="{{section.elementWithParam(data)}}`
- In test
-- `data` = `{{mydata.value}}`
-- `section` = `existingSection`
- Above now correctly fetches and resolves `{{existingSection.elementWithParam(mydata.value)}}`
> MQE-1222: Selector Fails To Resolve Correctly in Action Group

- src/Magento/FunctionalTestingFramework/Extension/ErrorLogger.php
- Syntax issue in ErrorLogger.php fixed.
> MQE-1117: dontSeeJsError does not catch JS errors

- .github/CONTRIBUTING.md
Copy content from devdocs
Convert to GFM
Review and update
Add table of contents
Add CONTRIBUTING.md with the guidelines from the [corresponding devdocs topic](https://devdocs.magento.com/guides/v2.2/magento-functional-testing-framework/contribution-guidelines.html) to follow the common GitHub recommendations and the magento2 repo structure.
> MAGEDOC-3161: Create CONTRIBUTING.md

- dev/tests/unit/Magento/FunctionalTestFramework/Util/ModuleResolverTest.php
- src/Magento/FunctionalTestingFramework/Test/Config/Dom.php
- src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
Modified Module Resolver to restrict search areas for MFTF Tests
> MQE-1288: ModuleResolver test paths are too greedy

- README.md
Update the Contribution Guidelines link to point to `.github/CONTRIBUTING.md`.
2. ...
> MAGEDOC-3187: Change the Contribution Guidelines link in README

- src/Magento/FunctionalTestingFramework/Exceptions/Collector/ExceptionCollector.php
Hello,
In my opinion, No $key variables are required.
Because it is not used.
What do you think of it?
Thanks.
N/A
> Removed unused variables

- src/Magento/FunctionalTestingFramework/Console/CommandList.php
- src/Magento/FunctionalTestingFramework/Console/RunTestFailedCommand.php
Adding a run:failed command to run the tests that failed on the last build
> MQE-1260: Create RERUN_COUNT field in Jenkins MFTF Parameters section same as MTF parameters section

- dev/tests/unit/Magento/FunctionalTestFramework/Util/ModuleResolverTest.php
- src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
- Removed all trimming of "Magento_" from enabled modules in ModuleResolver
- Removed all trimming of "*_" from module name in ModuleResolver
> MQE-1330: FT can not be executed for bundled extensions

- CHANGELOG.md
- bin/mftf
- composer.json
- composer.lock
- Added Changelog entry
- Changed version in composer and lock file
> MQE-1336: Add Changelog entry and bump composer version

- CHANGELOG.md
- src/Magento/FunctionalTestingFramework/Page/Handlers/SectionObjectHandler.php
- If an element has no type, it will cause a warning if it's parsed during a test run. This will lead to the test execution being aborted due to this warning, and thus no test artifacts.
> Fix Element with no type attribute warnings

- CHANGELOG.md
- bin/mftf
- composer.json
- composer.lock
- src/Magento/FunctionalTestingFramework/Console/RunTestFailedCommand.php
- RunTestFailedCommand now trims "_#" if it is present
> MQE-1357: mftf run:failed cannot regenerate parallelized suites

- dev/tests/_bootstrap.php
- dev/tests/verification/Resources/ExtendedTestInSuiteChildTestCest.txt
- dev/tests/verification/TestModule/Test/ExtendedFunctionalTest.xml
- dev/tests/verification/Tests/SuiteGenerationTest.php
- dev/tests/verification/_suite/functionalSuiteExtends.xml
- src/Magento/FunctionalTestingFramework/Test/Handlers/TestObjectHandler.php
> MQE-1178: MFTF Generate:Suite Does Not Generate Extended Items Correctly

- dev/tests/verification/Resources/SectionReplacementTest.txt
- dev/tests/verification/TestModule/Section/SampleSection.xml
- dev/tests/verification/TestModule/Test/SectionReplacementTest.xml
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
> Mqe 1361: Unable to use empty string literal as argument to selector in tests

- dev/tests/verification/Resources/functionalSuiteHooks.txt
- etc/config/codeception.dist.yml
- src/Magento/FunctionalTestingFramework/Allure/Adapter/MagentoAllureAdapter.php
- src/Magento/FunctionalTestingFramework/Extension/TestContextExtension.php
- src/Magento/FunctionalTestingFramework/Suite/views/SuiteClass.mustache
- Removed use of Codeception\Extension\RunFailed
- Moved RunFailed functionality to TestContextExtension, to be able to write incomplete tests to the `failed` file (for build reasons)
- Incomplete tests are now set as failed in MagentoAllureAdapter
> MQE-1372: If Suite before fails build must be RED

- dev/tests/verification/Resources/ExtendedChildTestInSuiteCest.txt
- dev/tests/verification/Resources/ExtendedChildTestNotInSuite.txt
- dev/tests/verification/TestModule/Test/ExtendedFunctionalTest.xml
- dev/tests/verification/Tests/ExtendedGenerationTest.php
- dev/tests/verification/Tests/SuiteGenerationTest.php
- dev/tests/verification/_suite/functionalSuiteExtends.xml
- src/Magento/FunctionalTestingFramework/Test/Handlers/TestObjectHandler.php
> MQE-1302: MFTF Remove Action Not Working For Extended Test

- etc/config/command.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Persist/Curl/WebapiExecutor.php
- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
> MQE-1353 & 1354

- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/CredentialStore.php
After this pull request is merged your secret value in `.credentials` can include the `=` character as part of its value
1. N/A
> Allow = to be part of the secret value

- src/Magento/FunctionalTestingFramework/Extension/TestContextExtension.php
- added \ to codeception usage.
> MQE-1152: Remove redundant after execution for codeception 2.4.4

- CHANGELOG.md
- bin/mftf
- composer.json
- composer.lock
- Added 2.3.13 changelog and bumped version in composer/lock file
> MQE-1417: Changelog and Version Bump

- CHANGELOG.md
- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
- Bug fix in MQE-1185 found to create backwards incompatibility
- Reverting fix and changelog for inclusion in MFTF 3.0.0
> Revert MQE-1185

- CHANGELOG.md
- bin/mftf
- composer.json
- composer.lock
> MFTF 2.3.14 - Merge develop to master

- etc/config/command.php
> MQE-1428: CLI command.php treats argument "0" as null

- .travis.yml
- bin/phpunit-checks
- composer.json
- composer.lock
Add support for php 7.3
* add php 7.3 to .travis.yml
- Initial successful build on travis - skips coverage check on 7.3 image due to lack of stable xdebug support.
* update `brainmaestro/composer-git-hooks` to `v2.6.1`
- The update to this package was only a commit bumping the version number https://github.com/BrainMaestro/composer-git-hooks/commit/137dd2aec2be494918f8bdfb18f57b55ff20015e
>  Update requirements to include php7.3 support

- src/Magento/FunctionalTestingFramework/Allure/Adapter/MagentoAllureAdapter.php
* Control characters break Allure report generation
* This change strips control characters
* When this is released, we can unskip MFTF testCaseId MAGETWO-96136
* [Here's a link to a build](http://10.234.200.213:8080/job/Functional-Tests-EE/790/allure/#suites/8187718e2fd144987673ef34ee62b41b/98636d84d0259c4d/) where this is fixed and MAGETWO-96136 is unskipped and ran
> MQE-1439: Invalid XML character in AdminDateFormatOnAttributePageTest causes Allure report parse error

- docs/commands/codeception.md
This PR fixes a typo in https://devdocs.magento.com/mftf/docs/commands/codeception.html#usage-examples
Fixes #4169.
> Fixed misspelling.

- docs/getting-started.md
Added Nginx specific settings to Getting Started doc. I was missing this info when I started to contribute to MFTF.
> Added Nginx specific settings to getting started doc

- dev/tests/verification/Resources/ExecuteInSeleniumTest.txt
- dev/tests/verification/TestModule/Test/ExecuteInSeleniumTest.xml
- dev/tests/verification/Tests/ExecuteInSeleniumTest.php
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
**executeInSelenium** action does not generate proper code because this action was not included in `ActionObject::FUNCTION_CLOSURE_ACTIONS`
1. Create test with **executeInSelenium** action 
`<executeInSelenium function="function ($webdriver) { return 'Hello, World!'}" stepKey="testStep"/>`
2. Run `vendor/bin/mftf generate:tests`
There is generated action
`$I->executeInSelenium(function ($webdriver) { return 'Hello, World!'});`
Function is passed as Closure.
There is generated action
`$I->executeInSelenium("function ($webdriver) { return 'Hello, World!'}");`
Function is passed as string not Closure. So if you run test you will get exception here.
> executeInSelenium action does not generate proper code

- src/Magento/FunctionalTestingFramework/Console/RunTestCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestFailedCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestGroupCommand.php
Return the already available exit codes of the spawned processes as return code for the commands
1. magento/magento2-functional-testing-framework#337: run:<x> command always returns exit code of 0
> Return exit codes of process started by 'run:test', 'run:group' or 'run:failed' command

- docs/commands/mftf.md
-  Added documentation for static-checks command.
> MQE-810: Create a static test to validate references between modules

- CHANGELOG.md
- bin/mftf
- composer.json
- composer.lock
- Added items to changelog
- Version bump in composer
> MQE-1529: Add release to CHANGELOG.MD

- docs/versioning.md
Adds a magento2 -> MFTF version table.
Adds instructions for updating MFTF.
> Add version table and update instructions.

- docs/data.md
MFTF will only read data nodes from files, which have the suffix `Data.xml`. I did not find a place where this is documented and I think it fits here.
> added file name suffix principle for data

- src/Magento/FunctionalTestingFramework/Codeception/Subscriber/Console.php
- Added constructor to Console class
> MQE-1622: MFTF Console Printer does not correctly consider --steps

- .gitignore
- src/Magento/FunctionalTestingFramework/Console/StaticChecksCommand.php
- src/Magento/FunctionalTestingFramework/StaticCheck/StaticCheckInterface.php
- src/Magento/FunctionalTestingFramework/StaticCheck/StaticCheckListInterface.php
- src/Magento/FunctionalTestingFramework/StaticCheck/StaticChecksList.php
- src/Magento/FunctionalTestingFramework/StaticCheck/TestDependencyCheck.php
The static-checks command now returns 1 if any errors are found and 0 if there are no errors.
https://jira.corp.magento.com/browse/MQE-1606
> MQE-1606: Mftf static check script should return error exit code when check fails

- src/Magento/FunctionalTestingFramework/Test/Config/Converter/Dom/Flat.php
- Added check for node parent when converting XML comment to action
> MQE-1669: XML Comments outside of Test and AG

- etc/config/command.php
- added strlen to prevent removal of "0"
- added bugfix for `argumentParts` array not being used
> MQE-1673: command.php truncating values '0'

- docs/selectors.md
This file was removed to mitigate build errors. We can put it back now.
> Putting selectors.md back

- CHANGELOG.md
- bin/mftf
- composer.json
- composer.lock
- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/PersistedObjectHandler.php
- Added try/catch logic to problem area.
> MQE-1715: .credentials file must exist but it should not have to

- docs/commands/mftf.md
- src/Magento/FunctionalTestingFramework/Console/CommandList.php
- src/Magento/FunctionalTestingFramework/Console/RunManifestCommand.php
I created a new run:manifest command which is able to run testManifest.txt files.
testManifest.txt files are created when tests are generated or can be crafted by hand to meet the user's needs.
> MQE-1626: bin/mftf run:manifest

- src/Magento/FunctionalTestingFramework/Console/BaseGenerateCommand.php
- src/Magento/FunctionalTestingFramework/Console/GenerateTestsCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestCommand.php
> MQE-1703: Implicit Suite Generation for Tests

- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
This pull request adds the screenshot to the allure report when the `makeScreenshot` action is used.
> MQE 1692: Improve makeScreenshot Action to Add Screenshot to Allure Report

- docs/metadata.md
> [DevDoc]MQE-1729: Added document for PR #377

- docs/commands/mftf.md
Cleans up a command that had errant "\r\n" that would break the command if copy/pasted.
> Removed breaking "\r\n" instances from command.

- src/Magento/FunctionalTestingFramework/Console/BaseGenerateCommand.php
- src/Magento/FunctionalTestingFramework/Console/GenerateSuiteCommand.php
- src/Magento/FunctionalTestingFramework/Console/GenerateTestsCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestFailedCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestGroupCommand.php
- Fix tag name to allow-skipped as per AC
> MQE-1582: Enable Testers To Run Skipped Tests

- docs/configuration.md
- docs/credentials.md
> MQE-1671: document using credentials with vault in MFTF tests

- docs/troubleshooting.md
- src/Magento/FunctionalTestingFramework/Console/BuildProjectCommand.php
This bug was reproducible on branches that had updated the `symfony/yaml` package in composer from v3.4.30 to v4.3.4. The updated package was less forgiving about our functional.suite.yml file which did not properly quote string values in some cases.
This PR only exists to ensure that in the future we get better output from the `mftf build:project` command. This output was hidden in the Jenkins job because the `--verbose` flag was not used. If we had that output in Jenkins, then this bug would have been trivial to identify.
I also added troubleshooting steps to devdocs for users on versions lower than MFTF 2.5.0.
TLDR: No bug here. I increased output from `mftf build:project` and wrote some docs.
1. https://jira.corp.magento.com/browse/MQE-1763
> MQE-1763: Investigate and fix failure due to absence of AcceptanceTester class

- docs/guides/selectors.md
- docs/guides/test-isolation.md
- docs/guides/test-modularity.md
- docs/guides/using-suites.md
In progress PR for our documentation work.
https://jira.corp.magento.com/browse/MQE-1706
> MQE-1706: Create training plan for core engineers and community

- dev/tests/unit/Magento/FunctionalTestFramework/Composer/ComposerInstallTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Composer/ComposerPackageTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Composer/_files/dir1/dir2/composer.json
- dev/tests/unit/Magento/FunctionalTestFramework/Composer/_files/dir1/dir2/composer.lock
- dev/tests/unit/Magento/FunctionalTestFramework/Composer/_files/dir1/dir2/dir31/composer.json
- dev/tests/unit/Magento/FunctionalTestFramework/Composer/_files/dir1/dir2/dir31/dir41/composer.json
- dev/tests/unit/Magento/FunctionalTestFramework/Composer/_files/dir1/dir2/dir32/composer.json
- dev/tests/unit/Magento/FunctionalTestFramework/Composer/_files/dir1/dir2/dir32/dir41/composer.json
- dev/tests/unit/Magento/FunctionalTestFramework/Composer/_files/dir1/dir2/dir32/dir42/composer.json
- dev/tests/unit/Magento/FunctionalTestFramework/Util/ComposerModuleResolverTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Util/ModuleResolverTest.php
- src/Magento/FunctionalTestingFramework/Util/ComposerModuleResolver.php
- src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
> MQE-1750: unit tests

- CHANGELOG.md
- bin/mftf
- composer.json
- composer.lock
- src/Magento/FunctionalTestingFramework/Console/GenerateSuiteCommand.php
This is a small hotfix to fix the broken `generate:suite` command that was missing a `use` statement.
-  [MQE-1816](https://jira.corp.magento.com/browse/MQE-1816) Fix missing MftfApplicationConfig import in GenerateSuiteCommand
> MFTF 2.5.1 Release Hotfix

- docs/merge_points/extend-data.md
The original text looks like it was copied from the Action Group extends article.
> Fix reference to action groups

- docs/suite.md
Various grammatical and formatting fixes
N/A
> Grammatical and formatting fixes

- docs/commands/mftf.md
Fixes the command name of static checks`. See https://github.com/magento/magento2-functional-testing-framework/blob/5a4909cc0de0ca9d201709a6e07aabe13e8610e5/src/Magento/FunctionalTestingFramework/Console/StaticChecksCommand.php#L35
> fixed static checks command name

- docs/getting-started.md
Add details to script the set up for Mftf
1. none
> Add details for changing settings via command line

- docs/commands/mftf.md
The example test cases do not exist and will give an error when you try to run them.
None
> Fixed example test cases to point to actual tests

- dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Persist/OperationDataArrayResolverTest.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Persist/OperationDataArrayResolver.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Util/OperationElementExtractor.php
If an array is defined for an entity it is currently not possible to
include different types of non primitive types in the same array.
E.g. it is not possible to add a product, whose "custom_attributes" field
should contain attributes that have a primitive type (e.g. url_key) and an
array type (e.g. category_ids)
This PR adds the ability to define multiple non primitive types for an array
type.
The definition of the CreateProduct request in 
magento-catalog/Test/Mftf/Metadata/product-meta.xml could be changed to
```xml
<array key="custom_attributes">
<value>custom_attribute_array</value>
<value>custom_attribute</value>
</array>
```
> Add possibility to include multiple non primitive types in an array

- composer.json
- composer.lock
- Reduced requirements of composer.json to 1.4 (magento 2.2)
> MQE-1650: update MFTF configuration to read Test entities from new location

- dev/tests/unit/Magento/FunctionalTestFramework/Extension/BrowserLogUtilTest.php
- docs/configuration.md
- etc/config/.env.example
- src/Magento/FunctionalTestingFramework/Extension/BrowserLogUtil.php
- src/Magento/FunctionalTestingFramework/Extension/ErrorLogger.php
- src/Magento/FunctionalTestingFramework/Extension/TestContextExtension.php
- Refactored ErrorLogger (no longer singleton, renamed for its actual use
- Added `stepAfter` actions to log browser logs
> MQE-1644: Add ability to see JS log in Allure 

- docs/guides/git-vs-composer-install.md
> [Documentation] MQE-1796: Magento Git vs Composer and MFTF

- docs/getting-started.md
New PR for #485. This time branched off master and merge to master
> Add webserver configuration to docs

- docs/credentials.md
Expanding on the usage section  in the Credentials docs. When trying to set up my project for use with MFTF Credentials the first time, I kept getting errors around the key not being found.
Turns out I was following the docs too explicitly. In the usage section, there is no mention of providing the vendor prefix in the key name, whereas in the section on how to add secrets (at least to File Storage), the instructions indicate to prefix your key names with a vendor prefix.
This PR, then, calls out how to use credentials and makes it explicit to, in the File Storage case, prefix your key name with the vendor.
Also tried to be explicit about different usage in File vs Vault Storage configurations, _but_, I have no experience with Vault Storage, so am assuming a lot about how to use it! This …
> expanding on credential usage docs

- composer.json
- composer.lock
- src/Magento/FunctionalTestingFramework/Extension/TestContextExtension.php
attaching suppressed exception before _after hook failure to current step.
2. ...
> MQE-1884: MFTF - <after> failures override other failures

- dev/tests/verification/Resources/PersistenceCustomFieldsTest.txt
- dev/tests/verification/TestModule/ActionGroup/PersistenceActionGroup.xml
- dev/tests/verification/TestModule/Test/PersistenceCustomFieldsTest.xml
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
- Testgenerator fix
- verification tests addition
* #317
> MQE-1627: RetrieveEntityField generation does not consider ActionGroup

- dev/tests/unit/Magento/FunctionalTestFramework/Allure/AllureHelperTest.php
- src/Magento/FunctionalTestingFramework/Allure/AllureHelper.php
- src/Magento/FunctionalTestingFramework/Allure/Event/AddUniqueAttachmentEvent.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Persist/CurlHandler.php
* Added allure artifacts + surrounding classes required to maintain uniqueness.
> MQE-1765: Introduce API Endpoint and Request Headers to Allure artifacts

- docs/suite.md
https://jira.corp.magento.com/browse/MQE-1463
> MQE-1463: Fixes for Suite documentation in devdocs

- src/Magento/FunctionalTestingFramework/Console/DoctorCommand.php
- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriverDoctor.php
> MQE-1908: Change doctor command to work with Curl version of MagentoCLI

- src/Magento/FunctionalTestingFramework/Extension/TestContextExtension.php
Fix for ENABLE_BROWSER_LOG=false not turning off logging.
2. ...
> MQE-1917: ENABLE_BROWSER_LOG = false attaches JS logs to allure

- CHANGELOG.md
- bin/mftf
- composer.json
- composer.lock
- CHANGELOG update
- Composer file and lock update
> MQE-1893: CHANGELOG.MD and Composer version bump

- docs/guides/selectors.md
-  Added clarity in the differences between `/` and `//` XPath selector syntax
> Added clarity in selector paths

- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
Set of changes to improve readability and performance of TestGenerator.
N/A
> Refactor of TestGenerator class

- docs/extending.md
Remove extra spaces from <tests> node in example code blocks
https://devdocs.magento.com/mftf/docs/extending.html
> Remove extra spaces

- docs/best-practices.md
- docs/test/action-groups.md
Briefly updated the Documentation contents.
1. magento/magento2-functional-testing-framework#501
> #501 Update MFTF documentation and Best Practices

- docs/commands/mftf.md
- src/Magento/FunctionalTestingFramework/Console/StaticChecksCommand.php
> MQE-1959: Static-checks command can be configured

- README.md
This PR updates a broken link in the Readme file for the MFTF Contribution Guidelines. The existing link produces a 404 error.
File affected: https://github.com/magento/magento2-functional-testing-framework/blob/develop/README.md
Changed existing link (.github/CONTRIBUTING.html) to https://github.com/magento/magento2-functional-testing-framework/blob/develop/.github/CONTRIBUTING.md
> updated Contribution Guidelines link

- CHANGELOG.md
- composer.json
- composer.lock
> MQE-1969: Updated CHANGELOG.md and bumped MFTF package version

- docs/data.md
- docs/metadata.md
- docs/page.md
- docs/section.md
- docs/section/locator-functions.md
- docs/test.md
- docs/test/action-groups.md
This PR adds information about the new `deprecation` tag.
1. https://jira.corp.magento.com/browse/MQE-1983
> Adding deprecation attribute info

- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
The issue with `[PHPUnit\Framework\Exception] max(): Array must contain at least one element` appears only when no groups provided. That's why I return `0` when there's no entry for `$this->cronExecution`
N/A
> Quick Fix: PHP's max() requires at least 1 argument

- dev/tests/verification/Resources/BasicFunctionalTest.txt
- dev/tests/verification/Resources/ExecuteInSeleniumTest.txt
- docs/test/actions.md
- src/Magento/FunctionalTestingFramework/Console/BaseGenerateCommand.php
- src/Magento/FunctionalTestingFramework/Console/GenerateSuiteCommand.php
- src/Magento/FunctionalTestingFramework/Console/GenerateTestsCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestFailedCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestGroupCommand.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
> MQE-1986: Mark `executeInSelenium` and `performOn` as deprecated in MFTF

- CHANGELOG.md
- composer.json
- composer.lock
moved facebook/webdriver to replace
added php-webdriver/webdriver
2. ...
> MQE-1988: MFTF failures after PHP upgrade (libzip5 v1.60+)

- docs/test/actions.md
This PR fixes an error in the example code for `seeNumberOfElements` on the Actions topic.
https://devdocs.magento.com/mftf/docs/test/actions.html#seenumberofelements
> Fixes a code example on the Actions page.

- CHANGELOG.md
- composer.json
- composer.lock
- dev/tests/verification/Resources/AssertTest.txt
- dev/tests/verification/TestModule/Test/AssertTest.xml
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
> Mqe 1997: Type float is wrongly treated as integer in assert actions

- docs/getting-started.md
1. Cache clean command added after changing the configuration values in Magento admin.
2. Configuration path is updated and information on Nginx server configuration updated.
> MFTF Getting Started page improvements

- CHANGELOG.md
- composer.json
- composer.lock
- dev/tests/functional/tests/MFTF/DevDocs/Test/DeprecatedDevDocsTest.xml
- dev/tests/unit/Magento/FunctionalTestFramework/Suite/Handlers/SuiteObjectHandlerTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Suite/SuiteGeneratorTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Handlers/TestObjectHandlerTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/ObjectExtensionUtilTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Util/TestGeneratorTest.php
- docs/commands/mftf.md
- src/Magento/FunctionalTestingFramework/Config/MftfApplicationConfig.php
- src/Magento/FunctionalTestingFramework/Console/BaseGenerateCommand.php
- src/Magento/FunctionalTestingFramework/Console/GenerateTestsCommand.php
- src/Magento/FunctionalTestingFramework/Filter/FilterInterface.php
- src/Magento/FunctionalTestingFramework/Filter/FilterList.php
- src/Magento/FunctionalTestingFramework/Filter/Test/Severity.php
- src/Magento/FunctionalTestingFramework/Suite/Objects/SuiteObject.php
- src/Magento/FunctionalTestingFramework/Suite/SuiteGenerator.php
- src/Magento/FunctionalTestingFramework/Test/Handlers/TestObjectHandler.php
- src/Magento/FunctionalTestingFramework/Test/Parsers/TestDataParser.php
- src/Magento/FunctionalTestingFramework/Util/Logger/MftfLogger.php
- src/Magento/FunctionalTestingFramework/Util/Manifest/DefaultTestManifest.php
- src/Magento/FunctionalTestingFramework/Util/Manifest/ParallelTestManifest.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
> MQE-2008: Filter test generation and execution by severity

- dev/tests/unit/Magento/FunctionalTestFramework/Test/Objects/ActionObjectTest.php
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
After merging this PR, we were unable to generate tests due to a `{{AdminUrlRewriteEditPage.url}}` reference that was missing an argument in 3 places. I tried everything I could think of to figure out how to fix the XML but could not find what the problem was.
We agreed to revert it so that we can have green builds on our 3.0.0 branches. We will look further into this asap.
TLDR: I'm reverting #546
> Revert "Merge pull request #546 from lbajsarowicz/bugfix/55-missing-url-attribute"

- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/DataObjectHandler.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/OperationDefinitionObjectHandler.php
- src/Magento/FunctionalTestingFramework/Page/Handlers/PageObjectHandler.php
- src/Magento/FunctionalTestingFramework/Page/Handlers/SectionObjectHandler.php
- src/Magento/FunctionalTestingFramework/Test/Handlers/ActionGroupObjectHandler.php
- src/Magento/FunctionalTestingFramework/Test/Handlers/TestObjectHandler.php
- src/Magento/FunctionalTestingFramework/Util/Validation/NameValidationUtil.php
Build:
https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/30465/
Note: This build has failures around video tests, but this is also a problem in mainline right now too.
> MQE-2016: Add warning for test materials that violate naming convention

- .travis.yml
- CHANGELOG.md
- composer.json
- composer.lock
- src/Magento/FunctionalTestingFramework/Allure/Event/AddUniqueAttachmentEvent.php
[MQE-2052](https://jira.corp.magento.com/browse/MQE-2052): MFTF uses undeclared dependency
> MQE-2052: MFTF uses undeclared dependency

- dev/tests/functional/standalone_bootstrap.php
- src/Magento/FunctionalTestingFramework/Config/FileResolver/Root.php
Added dev/tests/acceptance path of _suite to file to getFileCollection() if it's a valid path
2. ...
> MQE-2040: Unable to run suites from standalone MFTF

- etc/codecoverage/index.php
- etc/codecoverage/test.php
- src/Magento/FunctionalTestingFramework/Extension/TestContextExtension.php
Modify TestContextExtension to call test.php file to keep track of test name during code coverage gathering.
Controlled by a new environment variable called `ENABLE_CODE_COVERAGE`.
> MQE-2042: Port MFTF Coverage to Jenkins

- docs/commands/mftf.md
- src/Magento/FunctionalTestingFramework/Config/FileResolver/Root.php
- src/Magento/FunctionalTestingFramework/Console/StaticChecksCommand.php
- src/Magento/FunctionalTestingFramework/StaticCheck/DeprecatedEntityUsageCheck.php
- src/Magento/FunctionalTestingFramework/StaticCheck/StaticChecksList.php
- src/Magento/FunctionalTestingFramework/StaticCheck/TestDependencyCheck.php
- src/Magento/FunctionalTestingFramework/Test/Objects/TestObject.php
- src/Magento/FunctionalTestingFramework/Test/Util/TestObjectExtractor.php
- src/Magento/FunctionalTestingFramework/Util/Script/ScriptUtil.php
> MQE-1957: Entity Deprecation Reference - Static Check

- dev/tests/functional/tests/MFTF/DevDocs/ActionGroup/HelperActionGroup.xml
- dev/tests/functional/tests/MFTF/DevDocs/Test/DevDocsTest.xml
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionGroupObject.php
> MQE-2043 Custom helper argument in action group is not resolved

- docs/getting-started.md
As we have the execution mentioned as an example, mentioning a specific version; I added the download command into the example, to help developers run the same example mentioned if they don't have download it before.
> Adding the Selenium server download in the example

- docs/test.md
My main goal was to update the purpose of `<before>` and `<after>` section.
By the way I've updated the rest of documentation to point out that there's only one `Test` allowed per file.
N/A
> DevDocs: Update documentation regarding Test object.

- CHANGELOG.md
- docs/commands/mftf.md
- Updated 3.0.0 RC2 changelog
- Added missing documentation
2. ...
> MQE-2097: CHANGELOG.MD and Composer version bump

- docs/custom-helpers.md
> MQE-2034: Document Custom Helper functionality

- src/Magento/FunctionalTestingFramework/StaticCheck/ActionGroupArgumentsCheck.php
- src/Magento/FunctionalTestingFramework/Upgrade/RemoveUnusedArguments.php
- src/Magento/FunctionalTestingFramework/Upgrade/UpgradeScriptList.php
- Refactored ActionGroupArgumentsCheck.php to use DomDocument traversals instead of reg-ex
- Reused static-check methods for removal of unused arguments
2. ...
> MQE-2045: Upgrade script to remove unused arguments

- docs/configure-2fa.md
- docs/getting-started.md
- docs/test/actions.md
> MQE-2122: MFTF 2FA documentation

- src/Magento/FunctionalTestingFramework/Util/Logger/MftfLogger.php
Changed deprecation and notices to suppress logging during test execution
2. ...
> MQE-2143: Cleanup mftf.log

- docs/backward-incompatible-changes.md
> MQE-2141: MFTF BIC Documentation

- etc/config/functional.suite.dist.yml
This is required for Chrome 81.
It is also safe for Chrome 65 because Chrome 65 already launches with this new flag in Jenkins. Mike helped me confirm that.
> MQE-2161: Chrome 81 requires --ignore-certificate-errors flag

- CHANGELOG.md
> MQE-2153: CHANGELOG.md updated for 3.0.0-RC4

- dev/tests/verification/Resources/functionalSuiteHooks.txt
- dev/tests/verification/Resources/functionalSuiteWithComments.txt
- docs/configuration.md
- etc/config/.env.example
- etc/config/functional.suite.dist.yml
- src/Magento/FunctionalTestingFramework/Suite/views/SuiteClass.mustache
- src/Magento/FunctionalTestingFramework/Suite/views/partials/testActions.mustache
- [MQE-2162](https://jira.corp.magento.com/browse/MQE-2162): Chrome remains running after MFTF suite finishes
- https://m2build-ur-stg.devops.magento.com/job/All-User-Requested-Tests/1168/
> MQE-2162: Chrome remains running after MFTF suite finishes

- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
> MQE-2140: [chrome81] dragAndDrop with x and y offsets no longer works

- src/Magento/FunctionalTestingFramework/Module/MagentoPwaWebDriver.php
- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
- Adding locators to wait for in PWA webdriver
- Updating Magento webdriver to correctly use loading icon locators
- Updating Magento webdriver to use pageload_timeout
2. ...
> PWA-691: Fix Waits In PWA MFTF MagentoPwaWebDriver

- dev/tests/verification/Resources/PageReplacementTest.txt
- src/Magento/FunctionalTestingFramework/DataGenerator/Persist/Curl/AbstractExecutor.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Persist/Curl/AdminExecutor.php
- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriverDoctor.php
- src/Magento/FunctionalTestingFramework/Provider/UrlProvider.php
- src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
Finally - for `admin` area I've changed the method from `amOnPage` to `amOnUrl`. This solution works like a charm. Also introduced the single class to provide proper URL, as it was done inconsistently across the application
1. magento/magento2-functional-testing-framework#389
> #389 Fix invalid bahaviour of MAGENTO_BACKEND_BASE_URL

- CHANGELOG.md
consolidated change log for 3.0.0
2. ...
> MQE-2203: Create CHANGELOG.MD entry for 3.0.0

- docs/merge_points/extend-action-groups.md
- docs/merge_points/extend-data.md
- docs/merge_points/extend-tests.md
- docs/merge_points/merge-action-groups.md
- docs/merge_points/merge-sections.md
- docs/merge_points/merge-tests.md
> Mqe 2215:  Docs Annual Review Part 2

- docs/best-practices.md
> MQE-2218: Part 5 Docs Annual Review

- docs/test/actions.md
- docs/test/annotations.md
- docs/versioning.md
> MQE-2217: Part 4 Docs Annual Review

- docs/section.md
- docs/section/locator-functions.md
- docs/suite.md
- docs/update.md
> MQE-2219: Part 6 Docs Annual Review

- docs/data.md
Improved the Data entity MFTF document by providing examples for each data entity node.
Added example from the already defined MFTF test for each sub-topic.
- https://devdocs.magento.com/mftf/docs/data.html
> Data entity document improvement

- docs/guides/cicd.md
> MQE-2223: Part 7 Docs Review "MFTF Ease Of Use" PR #483

- .github/CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- README.md
> [master] MQE-2231: Adobe open source repository standards compliance

- .gitignore
Adds the v2 folder to gitignore so we properly handle versioned docs.
> Add v2 folder to gitignore for versioned docs.

- dev/tests/_bootstrap.php
- dev/tests/util/MftfStaticTestCase.php
- dev/tests/verification/PauseCheckModule/ActionGroup/ActionGroupWithMultiplePausesActionGroup.xml
- dev/tests/verification/PauseCheckModule/ActionGroup/ActionGroupWithNoPauseActionGroup.xml
- dev/tests/verification/PauseCheckModule/ActionGroup/ActionGroupWithPauseActionGroup.xml
- dev/tests/verification/PauseCheckModule/Suite/suiteWithMultiplePauseActionsSuite.xml
- dev/tests/verification/PauseCheckModule/Suite/suiteWithPauseActionSuite.xml
- dev/tests/verification/PauseCheckModule/Test/TestWithMultiplePauseActionsTest.xml
- dev/tests/verification/PauseCheckModule/Test/TestWithPauseActionTest.xml
- dev/tests/verification/Resources/StaticChecks/mftf-pause-action-usage-checks.txt
- dev/tests/verification/Tests/StaticCheck/PauseActionStaticCheckTest.php
- docs/commands/mftf.md
- src/Magento/FunctionalTestingFramework/Console/StaticChecksCommand.php
- src/Magento/FunctionalTestingFramework/StaticCheck/PauseActionUsageCheck.php
- src/Magento/FunctionalTestingFramework/StaticCheck/StaticChecksList.php
- src/Magento/FunctionalTestingFramework/Util/Script/ScriptUtil.php
> MQE-2242: Add static check to flag use of <pause>

- composer.json
- composer.lock
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Handlers/TestObjectHandlerTest.php
- docs/commands/mftf.md
- docs/configuration.md
- docs/interactive-pause.md
- docs/test/actions.md
- etc/config/.env.example
- src/Magento/FunctionalTestingFramework/Console/BaseGenerateCommand.php
- src/Magento/FunctionalTestingFramework/Console/Codecept/CodeceptCommandUtil.php
- src/Magento/FunctionalTestingFramework/Console/CodeceptRunCommand.php
- src/Magento/FunctionalTestingFramework/Console/CommandList.php
- src/Magento/FunctionalTestingFramework/Console/RunManifestCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestFailedCommand.php
- src/Magento/FunctionalTestingFramework/Console/RunTestGroupCommand.php
- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
- src/Magento/FunctionalTestingFramework/Test/Util/TestHookObjectExtractor.php
> MQE-2110: MFTF command to pause test execution

- CHANGELOG.md
- composer.json
- composer.lock
- docs/test/actions.md
> MQE-2258: CHANGELOG.MD and Composer version bump

- docs/commands/mftf.md
- docs/getting-started.md
- docs/update.md
Fixes documentation to have correct `generate:urn-catalog` examples.
> MQE-2289: Cant generate urn catalog

- dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Persist/OperationDataArrayResolverTest.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Persist/OperationDataArrayResolver.php
In case you extend an entity that has a requiredEntity and add a requiredEntity of the same type, then the requiredEntity of the
base entity is used.
This pull request changes this behaviour, so that the last requiredEntity of that specific type is used. This enables you to change
the content of a requiredEntity when extending an entity.
```xml
<entity name="BaseEntity" type="entity">
<data key="test">Test</data>
<requiredEntity type="subentity">BaseSubentity</requiredEntity>
</entity>
<entity name="BaseSubentity" type="subentity">
<data key="subtest">BaseSubtest</data>
</entity>
<entity name="ExtEntity" type="entity" extends="BaseEntity">
<requiredEntity type="subentity">ExtSubentity</requiredEntity>
</entity>
<entity name="ExtSubentity" type="subentity">
<data …
```
> Enable an extending entity to overwrite a requiredEntity binding

- docs/test.md
- docs/test/assertions.md
This PR adds example code snippets for the assert nodes and also updated the invalid external URL links with the correct URLs.
1. https://devdocs.magento.com/mftf/docs/test/assertions.html
2. https://devdocs.magento.com/mftf/docs/test.html
> Added examples and modified url links

- composer.json
- composer.lock
This PR updates `allure-codeception` to version 1.5 in order to bring compatibility with PHP8. It is needed in order to resolve dependencies issue for https://github.com/magento/magento2/pull/32614
2. ...
> Update allure-codeception in order to support php8

- composer.json
- composer.lock
- src/Magento/FunctionalTestingFramework/Config/Reader/Filesystem.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/PersistedObjectHandler.php
- src/Magento/FunctionalTestingFramework/Test/Util/ActionObjectExtractor.php
- src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
Updated monolog/monolog to `^2.2` as part of the "Platform Health" updates in the main repo.
- https://github.com/magento/magento2/pull/33226
- https://github.com/magento/partners-magento2ee/pull/555
- https://github.com/magento/magento2/issues/32868
> Updated monolog/monolog to ^2.2

- dev/tests/verification/Resources/BasicFunctionalTest.txt
- dev/tests/verification/TestModule/Test/BasicFunctionalTest/BasicFunctionalTest.xml
- src/Magento/FunctionalTestingFramework/DataTransport/Auth/Tfa/OTP.php
- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
- src/Magento/FunctionalTestingFramework/Test/etc/Actions/customActions.xsd
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
Improve Extendability of OTP implementation. 
The current implementation of the OTP works well for use with Magento's admin. It can even be used for other use cases. What is not possible in its current form is accessing multiple OTPs within the same test run. This is for example needed when trying to configure a Magento admin setting based on a value provided by a 3rd party also behind a 2FA.
Even changing the shared secret on the fly with something like   `<magentoCLI command="security:tfa:google:set-secret admin {{_CREDS.fooman/other/OTP_SHARED_SECRET}}" stepKey="setSecret"/>`  
does not work as the OTP is only initialised once.
This PR allows providing a separate secret 
`<getOTP stepKey="getOtherOtp" userInput="fooman/other/OTP_SHARED_SECRET"/>`  
with  
`<getOTP stepKey="getOtp" />` …
> Add ability to configure multiple OTPs

- dev/tests/unit/Magento/FunctionalTestFramework/Config/Reader/FilesystemTest.php
- src/Magento/FunctionalTestingFramework/Config/Reader/Filesystem.php
`codeception/aspect-mock` library is still not compatible with PHP 8.0 at the time of the creation of this ticket.
To speed up Magento compatibility with new PHP versions we'd like to eliminate `codeception/aspect-mock` dependency from MFTF. This will make MFTF compatible with PHP 8.0 that is required for declaring the Magento core PHP 8 compatible as well.
In order to do this existing unit tests using AspectMock should be refactored to use PHPUnit instead.
Resolves https://github.com/magento/magento2/issues/33291
Replace AspectMock with PHPUnit for `dev/tests/unit/Magento/FunctionalTestFramework/Config/Reader/FilesystemTest.php` in https://github.com/magento/magento2-functional-testing-framework repository.
Mocking an object using AspectMock (current):
```
$mock = AspectMock::double( …
```
> Eliminated Aspect Mock usage from FilesystemTest

- dev/tests/unit/Magento/FunctionalTestFramework/StaticCheck/AnnotationsCheckTest.php
Removed usage of AspectMock in `\tests\unit\Magento\FunctionalTestFramework\StaticCheck\AnnotationsCheckTest`
1. https://github.com/magento/magento2/issues/33288: [MFTF] Replace AspectMock with PHPUnit for AnnotationsCheckTest
Resolves https://github.com/magento/magento2/issues/33288
> Removed usage of AspectMock in AnnotationsCheckTest.php

- dev/tests/unit/Magento/FunctionalTestFramework/StaticCheck/DeprecatedEntityUsageCheckTest.php
Removed usage of AspectMock in `\tests\unit\Magento\FunctionalTestFramework\StaticCheck\DeprecatedEntityUsageCheckTest`
1. https://github.com/magento/magento2/issues/33298
Resolves https://github.com/magento/magento2/issues/33298
> Removed usage of AspectMock in DeprecatedEntityUsageCheckTest

- dev/tests/unit/Magento/FunctionalTestFramework/Util/GenerationErrorHandlerTest.php
I've eliminated AspectMock usage from `dev/tests/unit/Magento/FunctionalTestFramework/Util/GenerationErrorHandlerTest.php`
1.Fixes  magento/magento2#33307
> 33307: Eliminated AspectMock usage from GenerationErrorHandlerTest.php

- dev/tests/unit/Magento/FunctionalTestFramework/Console/BaseGenerateCommandTest.php
Eliminate AspectMock usage from `dev/tests/unit/Magento/FunctionalTestFramework/Console/BaseGenerateCommandTest.php`
1. magento/magento2#33292: [MFTF] Replace AspectMock with PHPUnit for BaseGenerateCommandTest #33292
> 33292 replace AspectMock from BaseGenerateCommandTest

- dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Util/DataExtensionUtilTest.php
- dev/tests/unit/Util/MagentoTestCase.php
Eliminated AspectMock usage from `dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Util/DataExtensionUtilTest.php`
1. Fixes magento/magento2#33297: [MFTF] Eliminate AspectMock from DataExtensionUtilTest (Complex!)
> Issue 33297: Eliminate AspectMock from DataExtensionUtilTest

- dev/tests/unit/Magento/FunctionalTestFramework/Test/Objects/ActionGroupObjectTest.php
Eliminated AspectMock usage from the \tests\unit\Magento\FunctionalTestFramework\Test\Objects\ActionGroupObjectTest
1. magento/magento2#33302: Eliminate AspectMock from ActionGroupObjectTest (Complex!)
> MFTF-33302: Eliminated AspectMock from ActionGroupObjectTest

- dev/tests/unit/Magento/FunctionalTestFramework/Util/GenerationErrorHandlerTest.php
I've removed not used mock object from GenerationErrorHandlerTest.php
1. Fixes magento/magento2#33307: Eliminated AspectMock usage from GenerationErrorHandlerTest.php
> 33307: Removed not used mocked object

- dev/tests/unit/Magento/FunctionalTestFramework/Test/Objects/ActionObjectTest.php
- dev/tests/unit/Util/MagentoTestCase.php
Eliminated usage of AspectMock from the \tests\unit\Magento\FunctionalTestFramework\Test\Objects\ActionObjectTest.
1. magento/magento2#33303: [MFTF] Eliminate AspectMock from ActionObjectTest (Complex!)
> MFTF-33303: Eliminated AspectMock usage from ActionObjectTest

- dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Handlers/SecretStorage/FileStorageTest.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/CredentialStore.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/SecretStorage/FileStorage.php
Eliminated AspectMock usage from `dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Handlers/SecretStorage/FileStorageTest.php`
note: in this case, main complexity is in a private functions calls rather than static
1. Fixes magento/magento2#33295: [MFTF] Eliminate AspectMock from FileStorageTest (Complex!)
> 33295: Eliminate AspectMock from FileStorageTest

- dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Handlers/PersistedObjectHandlerTest.php
- dev/tests/unit/Util/MagentoTestCase.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Persist/CurlHandler.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Persist/DataPersistenceHandler.php
I've eliminated AspectMock usage from `dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Handlers/PersistedObjectHandlerTest.php`
1. Fixes magento/magento2#33293:[MFTF] Replace AspectMock with PHPUnit for PersistedObjectHandlerTest
> 33293: Eliminated AspectMock usage from PersistedObjectHandlerTest.php

- dev/tests/unit/Magento/FunctionalTestFramework/Util/TestGeneratorTest.php
- src/Magento/FunctionalTestingFramework/Util/Filesystem/CestFileCreatorUtil.php
- src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
I've eliminated AspectMock usage from 
`dev/tests/unit/Magento/FunctionalTestFramework/Util/TestGeneratorTest.php`.
1. Fixes magento/magento2#33309: [MFTF] Eliminate AspectMock from TestGeneratorTest (Complex!)
> 33309: Eliminated AspectMock usage from TestGeneratorTest.php

- dev/tests/unit/Util/TestLoggingUtil.php
Eliminated usage of AspectMock from the \tests\unit\Util\TestLoggingUtil.
1. magento/magento2#33585: [MFTF] Eliminate AspectMock from TestLoggingUtil (Complex!)
> MFTF-33585: Eliminated AspectMock usage from TestLoggingUtil

- dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Handlers/DataObjectHandlerTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Handlers/OperationDefinitionObjectHandlerTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Page/Handlers/PageObjectHandlerTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Page/Handlers/SectionObjectHandlerTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Handlers/ActionGroupObjectHandlerTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/ActionGroupAnnotationExtractorTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/AnnotationExtractorTest.php
I've eliminated AspectMock where it was imported but never used.
1. Fixes magento/magento2#33581
> 33581: Eliminated AspectMock where it was imported but never used

- dev/tests/unit/Magento/FunctionalTestFramework/Suite/Handlers/SuiteObjectHandlerTest.php
I've eliminated AspectMock usage from `dev/tests/unit/Magento/FunctionalTestFramework/Suite/Handlers/SuiteObjectHandlerTest.php`
1. Fixes magento/magento2#33300: [MFTF] Eliminate AspectMock from SuiteObjectHandlerTest (Complex!)
> 33300: Eliminated AspectMock usage from SuiteObjectHandlerTest.php

- dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/ObjectExtensionUtilTest.php
- dev/tests/unit/Util/MagentoTestCase.php
- dev/tests/unit/Util/MockModuleResolverBuilder.php
Eliminated AspectMock usage in the \tests\unit\Magento\FunctionalTestFramework\Test\Util\ObjectExtensionUtilTest.
1. magento/magento2#33305: [MFTF] Eliminate AspectMock from ObjectExtensionUtilTest (Complex!)
As the main idea of this issue to eliminate AspectMock usage in the ObjectExtensionUtilTest class, AspectMock usage eliminated only partially in the MockModuleResolverBuilder. It is a required action because in that class the \Magento\FunctionalTestingFramework\Util\ModuleResolver mocked instance hardcoded to be retrieved by the ObjectManager mocked object on its create method without any argument.
> MFTF-33305: Eliminate AspectMock from ObjectExtensionUtilTest

- dev/tests/unit/Magento/FunctionalTestFramework/Test/Handlers/TestObjectHandlerTest.php
Eliminated AspectMock usage for the \tests\unit\Magento\FunctionalTestFramework\Test\Handlers\TestObjectHandlerTest.
1. magento/magento2#33301: Eliminate AspectMock from TestObjectHandlerTest (Complex!)
> MFTF-33301: Eliminated AspectMock usage for TestObjectHandlerTest

- dev/tests/unit/Magento/FunctionalTestFramework/Suite/SuiteGeneratorTest.php
- src/Magento/FunctionalTestingFramework/Suite/Service/SuiteGeneratorService.php
- src/Magento/FunctionalTestingFramework/Suite/SuiteGenerator.php
I've eliminated AspectMock usage from `dev/tests/unit/Magento/FunctionalTestFramework/Suite/SuiteGeneratorTest.php`
1. Fixes magento/magento2#33299:[MFTF] Eliminate AspectMock from SuiteGeneratorTest (Complex!)
> 33299: Eliminated AspectMock usage from SuiteGeneratorTest.php

- dev/tests/unit/Magento/FunctionalTestFramework/Util/Sorter/ParallelGroupSorterTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Util/TestGeneratorTest.php
Eliminated usage of AspectMock from the \tests\unit\Magento\FunctionalTestFramework\Util\Sorter\ParallelGroupSorterTest.
1. magento/magento2#33306: [MFTF] Replace AspectMock with PHPUnit for ParallelGroupSorterTest
> 33306: Eliminated AspectMock from the ParallelGroupSorterTest class

- dev/tests/unit/Magento/FunctionalTestFramework/Allure/AllureHelperTest.php
- src/Magento/FunctionalTestingFramework/Allure/AllureHelper.php
- src/Magento/FunctionalTestingFramework/Allure/Event/AddUniqueAttachmentEvent.php
Eliminate AspectMock usage from `dev/tests/unit/Magento/FunctionalTestFramework/Allure/AllureHelperTest.php`
1. magento/magento2#33294: [MFTF] Eliminate AspectMock from AllureHelperTest (Complex!) #33294
> 33294 eliminate aspectmock from allureHelperTest

- dev/tests/unit/Magento/FunctionalTestFramework/Util/Path/FilePathFormatterTest.php
- dev/tests/unit/Magento/FunctionalTestFramework/Util/Path/UrlFormatterTest.php
- src/Magento/FunctionalTestingFramework/Util/Path/FilePathFormatter.php
- src/Magento/FunctionalTestingFramework/Util/Path/FormatterInterface.php
- src/Magento/FunctionalTestingFramework/Util/Path/UrlFormatter.php
I've investigated the impact of the new changes in parse_url() function for PHP 8 on the current MFTF codebase.
**Reported change (from the official documentation):**
_parse_url() will now distinguish absent and empty queries and fragments:_
```
http://example.com/foo → query = null, fragment = null
http://example.com/foo? → query = "", fragment = null
http://example.com/foo# → query = null, fragment = ""
http://example.com/foo?# → query = "", fragment = ""
```
_Previously all cases resulted in query and fragment being null._
In the MFTF codebase this function used only in the `\Magento\FunctionalTestingFramework\Util\Path\UrlFormatter` class.
I've added two data sets to the `\tests\unit\Magento\FunctionalTestFramework\Util\Path\UrlFormatterTest::formatDataProvider` to cover cases when …
> MFTF-33782: Added empty query and fragment testing to the UrlFormatterTest

- composer.json
- composer.lock
This pull request (PR) provides updating the `squizlabs/php_codesniffer` composer dependency to version 3.6.0 (latest).
1. magento/magento2#33832
> The `squizlabs/php_codesniffer` composer dependency has been updated to version 3.6.0

- src/Magento/FunctionalTestingFramework/DataTransport/Protocol/CurlTransport.php
- src/Magento/FunctionalTestingFramework/Extension/TestContextExtension.php
Fixed fragments of code related to changes in Curl in PHP 8 (where it was necessary) according to the document:
https://www.php.net/manual/en/migration80.incompatible.php
1. magento/magento2#33781: [MFTF] Investigate and fix code related to changes in CURL
> PHP 8 support - fix code related to changes in CURL

- composer.json
- composer.lock
- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/SecretStorage/VaultStorage.php
This PR aims to remove the dependency on Guzzle6transport, in order to be able to update the `guzzlehttp/guzzle` package to the latest `7.3.0` version. The current `csharpru/vault-php-guzzle6-transport` package's version, allows only `"guzzlehttp/guzzle": "~6.2"`.
N/A
> Removing the `csharpru/vault-php-guzzle6-transport` not needed dependency

- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
If some of the `REMOTE_STORAGE_` options contain `+` sign inside value the tests running will fail as here https://github.com/magento-commerce/magento2-functional-testing-framework/blob/develop/etc/config/command.php#L15 urldecode will remove pluses `+` from command and `setup:config:set --remote-storage-driver=...` will fail with `Too many arguments, expected arguments "command"`.
I got this issue as the current `REMOTE_STORAGE_AWSS3_SECRET_KEY` value contains two + signs.
I tried, with single quotes or double quotes but they are ignored and option values in command passing without quotes. 
For example, I’ve set:
`REMOTE_STORAGE_AWSS3_ACCESS_KEY='AKIAAFIELSFN+FNM7S2T+VORAXPQ'`
command.php received:
`php bin/magento setup:config:set ...  --remote-storage-key=AKIAAFIELSFN+FNM7S2T+VORAXPQ` …
> Fix encoding issue when secret key contains plus sign

- composer.json
- composer.lock
- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/SecretStorage/VaultStorage.php
- src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/SecretStorage/VaultTokenAuthStrategy.php
1. magento/magento2-functional-testing-framework#885
> Fix #885 - Implement correct params on Vault PHP lib call

- src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
When running `bin/magento cron:run`, several background processes are spawned. The intent of the `<magentoCron />` XML node is to run certain cron groups to completion. However, as the actual processing may happen in a background process, the test-suite typically does not behave as expected. (This is a race condition; see https://github.com/magento/magento2/pull/37511 for further details.)
This pull request solves this race condition by using the internal 'bootstrap' argument to indicate that the cron process is already standalone. This means that no additional background processes will be run and the jobs complete in the foreground process. The test-suite will then wait for this process to terminate before proceeding. This is the desired behaviour.
> Wait for cron process to finish properly

- dev/tests/unit/Magento/FunctionalTestFramework/Util/UnusedEntityCheckTest.php
- src/Magento/FunctionalTestingFramework/Allure/Adapter/MagentoAllureAdapter.php
- src/Magento/FunctionalTestingFramework/Config/Reader.php
- src/Magento/FunctionalTestingFramework/ObjectManager/Config/Reader/Dom.php
- src/Magento/FunctionalTestingFramework/StaticCheck/CreatedDataFromOutsideActionGroupCheck.php
- src/Magento/FunctionalTestingFramework/StaticCheck/UnusedEntityCheck.php
- src/Magento/FunctionalTestingFramework/Test/Objects/TestObject.php
This fixes most PHP 8.2 deprecated usages of 'creation of dynamic property': https://www.php.net/manual/en/migration82.deprecated.php#migration82.deprecated.core.dynamic-properties
The phpstan tool is able to find these problems:
```
$ /path/to/phpstan analyse --level=0 src | grep 'Access to an undefined property'
66     Access to an undefined property Magento\FunctionalTestingFramework\Allure\Adapter\MagentoAllureAdapter::$options.
67     Access to an undefined property Magento\FunctionalTestingFramework\Allure\Adapter\MagentoAllureAdapter::$options.
187    Access to an undefined property Magento\FunctionalTestingFramework\Allure\Adapter\MagentoAllureAdapter::$emptyStep.
51     Access to an undefined property Magento\FunctionalTestingFramework\Config\Reader::$isValidated.
68     Access …
```
> Fixed PHP 8.2 deprecation warnings: 'creation of dynamic property'.
