magento/magento2-functional-testing-framework

CHANGELOG.md
- Updated changelog.md with release contents.
=> MQE-821: [2.1.0 - Release] Changelog

CHANGELOG.md
- Added 2.1.1 contents to changelog.
=> MQE-853: [2.1.1 - Release] Changelog

src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
- appCode/VendorCode paths changed to meet AC.
=> MQE-918: Support for MFTF folder

composer.json, composer.lock
- fix symfony process dependency
2. ...
=> MQE-967: Resolve MFTF/Acceptance composer.json with Magento2CE

dev/tests/verification/Resources/ActionGroupUsingCreateData.txt, dev/tests/verification/TestModule/ActionGroup/BasicActionGroup.xml, dev/tests/verification/TestModule/Test/ActionGroupTest.xml, dev/tests/verification/Tests/ActionGroupGenerationTest.php, src/Magento/FunctionalTestingFramework/Test/Objects/ActionGroupObject.php
=> MQE-993: ActionGroups that use createData are not generated correctly

src/Magento/FunctionalTestingFramework/Console/BuildProjectCommand.php, src/Magento/FunctionalTestingFramework/Console/RunTestCommand.php, src/Magento/FunctionalTestingFramework/Console/RunTestGroupCommand.php
- Added timeout and idleTimeout optiosn to console commands.
=> MQE-1038: bin/mftf commands which exceed 60 seconds timeout

src/Magento/FunctionalTestingFramework/Upgrade/UpdateTestSchemaPaths.php
- Updated paths of all relevant paths.
=> MQE-1141: UpdateTestSchemaPaths broken due to updated relative paths

CHANGELOG.md
=> [2.3.0 - Release] Changelog

src/Magento/FunctionalTestingFramework/Console/BuildProjectCommand.php, src/Magento/FunctionalTestingFramework/Util/Logger/LoggingUtil.php
- added chmod to build:project command.
=> MQE-1147: make mftf.log visible on server

composer.json
=> MQE-1114: Merge the release branch to master

composer.lock, etc/config/command.php, src/Magento/FunctionalTestingFramework/Console/BuildProjectCommand.php
- command.php is now copied over on build:project.
- lock file update
=> MQE-1159: Verify if security vulnerability exists in MFTF

CHANGELOG.md
- created entry for MFTF 2.3.1
=> [2.3.1] CHANGELOG.md

CHANGELOG.md, composer.lock, etc/config/command.php, src/Magento/FunctionalTestingFramework/Console/BuildProjectCommand.php
- added command.php file
- added copy to build project
- lock file update for PHP7.0
=> MFTF 2.3.1: Merging Develop to Master

CHANGELOG.md
=> [2.3.2 - Release] Changelog

CHANGELOG.md, dev/tests/verification/Resources/ExecuteJsEscapingTest.txt, dev/tests/verification/Resources/ExtendingSkippedTest.txt, dev/tests/verification/Resources/SkippedTestWithHooks.txt, dev/tests/verification/TestModule/Test/ExecuteJsTest.xml, dev/tests/verification/TestModule/Test/ExtendedFunctionalTest.xml, dev/tests/verification/TestModule/Test/SkippedTest.xml, dev/tests/verification/Tests/ExtendedGenerationTest.php, dev/tests/verification/Tests/SkippedGenerationTest.php, src/Magento/FunctionalTestingFramework/Test/Objects/TestObject.php, src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
- Merging 2.3.1 contents to master
=> MFTF 2.3.2: Merging develop to master

CHANGELOG.md, composer.json
=> MQE-1171: Bump composer.json version

composer.json, composer.lock, etc/config/functional.suite.dist.yml
Correction functional suite changes for remote build executions
=> 2.3.3-Functional-Suite-Corrections

CHANGELOG.md, composer.json, composer.lock, etc/config/functional.suite.dist.yml
- Contents of MFTF 2.3.3 included (default config file changes)
=> MFTF 2.3.3 - Changelog and Version Bump

etc/config/functional.suite.dist.yml
- Added MagentoAssert module to config
=> Add MagentoAssert back to functional.dist.yml

CHANGELOG.md, composer.json, composer.lock, etc/config/functional.suite.dist.yml
=> MFTF 2.3.3 - Merge Develop to Master

src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php
=> MQE-1184: Describe which entity reference fails in generate:tests

CHANGELOG.md
=> MFTF 2.3.6 - CHANGELOG.md

bin/mftf, composer.json, composer.lock
=> MQE-1243: Commit proper version in MFTF composer.json/create the new release tag

CHANGELOG.md, bin/mftf, composer.json, composer.lock
- Changelog update with 2.3.7 items
- version bump in composer and lock file.
=> MFTF 2.3.7 - CHANGELOG.md and Version Bump

README.md
The PR introduces editorial changes in the README for:
- links
- formatting
- style
=> MAGEDOC-3174: Update README

CHANGELOG.md, bin/mftf, composer.json, composer.lock
- Changelog update with 2.3.8 items
- version bump in composer and lock file
=> MFTF 2.3.8 - CHANGELOG.md and Version Bump

README.md
=> Aligning the badges

.github/CONTRIBUTING.md, CHANGELOG.md, README.md, bin/mftf, composer.json, composer.lock, src/Magento/FunctionalTestingFramework/Extension/BaseExtension.php, src/Magento/FunctionalTestingFramework/Extension/ErrorLogger.php
- Merge 2.3.8 contents to master.
=> MFTF 2.3.8 - Merge to Master 

src/Magento/FunctionalTestingFramework/DataGenerator/Objects/OperationElement.php
=> MQE-1227: "Required" attribute value is skipped for metadata

src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
- bugfix for symlinked directories no longer following path correctly.
=> MQE-1330: FT can not be executed for bundled extensions

CHANGELOG.md, src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
- Fixed windows compatibility for Magento Module registration fetching.
=> Fix ModuleResolver windows compatibility

CHANGELOG.md, bin/mftf, composer.json, composer.lock, src/Magento/FunctionalTestingFramework/Console/RunTestFailedCommand.php
=> Merge Master to Develop

src/Magento/FunctionalTestingFramework/DataGenerator/Persist/Curl/FrontendExecutor.php
=> MQE-1145: Update FrontendExecutor::authorize() method.

etc/config/command.php
- Implemented timeout logic to CLI command
=> MQE-1444: Allow MagentoCLI to bypass wait for process

CHANGELOG.md, bin/mftf, composer.json, composer.lock
- Added release notes
- Updated .lock file and version
=> MQE-1449: Add release to CHANGELOG.MD

etc/config/codeception.dist.yml
- changed default config value in `codeception.dist.yml`
=> MQE-1534: MFTF not including flaky test retries in Allure Report

CHANGELOG.md, bin/mftf, composer.json, composer.lock
- Version bump
- Changelog Notes
=> MQE-1570: Add release to CHANGELOG.MD

src/Magento/FunctionalTestingFramework/Console/BuildProjectCommand.php
Fixed a spelling error that showed up in the command list that will end up in Devdocs.
=> Fixed spelling error.

CHANGELOG.md, bin/mftf, composer.json, composer.lock
- Changelog updated
- composer version bumped
=> MQE-1613: Add release to CHANGELOG.MD

docs/selectors.md
This PR adds the content that we came up with during our third devdocs meeting as a team.
=> MQE-1623: Add selector best practices to devdocs

dev/tests/verification/Resources/BasicFunctionalTest.txt, dev/tests/verification/Resources/DataReplacementTest.txt, dev/tests/verification/Resources/PersistedReplacementTest.txt, dev/tests/verification/TestModule/Test/BasicFunctionalTest.xml, dev/tests/verification/TestModule/Test/DataReplacementTest.xml, dev/tests/verification/TestModule/Test/PersistedReplacementTest.xml, dev/tests/verification/TestModule/Test/XmlDuplicateTest.xml, src/Magento/FunctionalTestingFramework/Test/Objects/ActionObject.php, src/Magento/FunctionalTestingFramework/Test/etc/Actions/dontSeeActions.xsd, src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
https://jira.corp.magento.com/browse/MQE-1636
This PR fixes and verifies that the `html` attribute works correctly for these actions:
* seeInPageSource
* dontSeeInPageSource
* seeInSource
* dontSeeInSource
=> MQE-1636: [GENERATOR] Page Source Actions are not quoted properly

dev/tests/verification/Resources/BasicFunctionalTest.txt, dev/tests/verification/TestModule/Test/BasicFunctionalTest.xml, src/Magento/FunctionalTestingFramework/Test/etc/Actions/dontSeeActions.xsd, src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
- allow schema to use either attribute and have testGenerator remap attributes
=> MQE-1679: dontSeeInPageSource BIC schema

etc/config/command.php
- Undoing 1510 contents, breaks functionality of existing tests
=> Undo MQE-1510

CHANGELOG.md, bin/mftf, composer.json, composer.lock
- Changelog update
- composer/lock file update
=> MQE-1657: Add release to CHANGELOG.MD

docs/getting-started.md
Minor change suggested to improve explanation of how to set up an embedded MFTF
2. ...
=> SMALL_CHANGE: Minor change suggested

dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Objects/EntityDataObjectTest.php, src/Magento/FunctionalTestingFramework/DataGenerator/Objects/EntityDataObject.php
Fixes bug [MQE-1306](https://jira.corp.magento.com/browse/MQE-1306) by adding a fallback checking for `camelCaseKeys` in data if now `lowercasekeys` are found.
=> MQE-1306: Can not get actual entity data

docs/getting-started.md
This PR fixes an issue where we had duplicate IDs assigned to headers.
https://devdocs.magento.com/mftf/docs/getting-started.html
=> Removes a duplicated ID from header

dev/tests/verification/Resources/functionalSuiteHooks.txt, dev/tests/verification/Resources/functionalSuiteWithComments.txt, src/Magento/FunctionalTestingFramework/Suite/views/SuiteClass.mustache
* [MQE-1691](https://jira.corp.magento.com/browse/MQE-1691): CREDS resolution does not occur from Suite <before>
magento/magento2-functional-testing-framework#412
=> MQE-1691: CREDS resolution does not occur from Suite <before>

CHANGELOG.md, bin/mftf, composer.json, composer.lock
- Version bump and changelog addition.
=> MQE-1699: CHANGELOG.MD and Composer version bump

docs/actiongroup-list.md
This PR adds the Action Group reference file to the MFTF docs repo.
=> Adding action group ref file.

src/Magento/FunctionalTestingFramework/DataGenerator/Objects/EntityDataObject.php
- Fixed potential bug in EntityDataObject
=> MQE-1705: Fix PHP Notice in Unit Test

etc/config/functional.suite.dist.yml
- Added quotes to default config
=> MQE-1628: Error loading Yaml config from

dev/tests/_bootstrap.php, dev/tests/unit/Magento/FunctionalTestFramework/Allure/AllureHelperTest.php, src/Magento/FunctionalTestingFramework/Allure/AllureHelper.php, src/Magento/FunctionalTestingFramework/DataGenerator/Persist/CurlHandler.php, src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
- Added AllureHelper class + unit tests
- Added calls to above class in MagentoWebDriver `see/dontsee` url actions + `CurlHandler` for persistence actions
=> MQE-1633 + MQE-1514

dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Handlers/DataObjectHandlerTest.php, dev/tests/unit/Magento/FunctionalTestFramework/Test/Handlers/ActionGroupObjectHandlerTest.php, dev/tests/unit/Magento/FunctionalTestFramework/Test/Handlers/TestObjectHandlerTest.php, dev/tests/unit/Magento/FunctionalTestFramework/Test/Util/ObjectExtensionUtilTest.php, dev/tests/unit/Util/ActionGroupArrayBuilder.php, src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/DataObjectHandler.php, src/Magento/FunctionalTestingFramework/Test/Handlers/ActionGroupObjectHandler.php, src/Magento/FunctionalTestingFramework/Test/Handlers/TestObjectHandler.php
=> Mqe 1685: Test/Data self extension memory limit error

src/Magento/FunctionalTestingFramework/Config/MftfApplicationConfig.php, src/Magento/FunctionalTestingFramework/Console/GenerateDocsCommand.php, src/Magento/FunctionalTestingFramework/Console/GenerateSuiteCommand.php, src/Magento/FunctionalTestingFramework/Console/GenerateTestsCommand.php, src/Magento/FunctionalTestingFramework/Console/RunTestCommand.php, src/Magento/FunctionalTestingFramework/Console/RunTestFailedCommand.php, src/Magento/FunctionalTestingFramework/Console/RunTestGroupCommand.php, src/Magento/FunctionalTestingFramework/StaticCheck/TestDependencyCheck.php
=> Mqe 1754 mftf generate:tests AdminLoginTest -f does not obey the -f flag

CHANGELOG.md
=> MQE-1671: updated CHANGELOG.md to include vault integration

docs/credentials.md
Two links had uppercase anchor links. This PR converts them to lowercase so devdocs doesn't break.
=> Fixed anchor links in credentials.md

docs/merge_points/extend-tests.md
The text should be about tests, not data objects
=> Fix reference to data objects

src/Magento/FunctionalTestingFramework/Util/ModuleResolver.php
=> MQE-1831: Remove Deprecation warning from Module Resolver

CHANGELOG.md, bin/mftf, composer.json, composer.lock, src/Magento/FunctionalTestingFramework/Allure/AllureHelper.php, src/Magento/FunctionalTestingFramework/StaticCheck/TestDependencyCheck.php
* Fixed allure exception in suite hooks
* Minor bugfix to static-checks (only present when no errors are found)
* Changelog and version bump
=> MFTF 2.5.3 + MQE-1870

docs/guides/action-groups.md
https://jira.corp.magento.com/browse/MQE-1845
=> MQE-1845: Convert Writing tests with actiongroups

etc/config/command.php
- command.php no longer overwrites potentially useful output with empty output
=> MQE-1712: Get Error HTTP response code: 500 when using magentoCLI

src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
Fix for pipeline step failures on execution of bin/magento from WebDriver. Needs investigation.
Builds are taking ~ 4 hours to execute.
UR build with the fix : https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/26883/
UR build (develop): https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/26866/
2. ...
=> MQE-1774: Review community PR #343

docs/merging.md
Provide a link to the corresponding section
1. Editorial
=> Add link to action-groups.md

CHANGELOG.md
=> 2.5.4 demo link

dev/tests/unit/Magento/FunctionalTestFramework/Util/TestGeneratorTest.php, src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
* Small refactor to TestGenerator to account for incorrect conditional.
* Added Unit test
=> MQE-1911: --allow-skipped removing test hooks

src/Magento/FunctionalTestingFramework/Console/RunTestGroupCommand.php
=> MQE-1761: Allure reporting error for multiple suite run

docs/mftf-tests.md
=> Fix include path to data file.

docs/test/action-groups.md
=> Adding back raw tag.

composer.lock, src/Magento/FunctionalTestingFramework/DataGenerator/Util/OperationElementExtractor.php
=> Update MFTF dependencies to latest possible version

dev/tests/verification/Resources/BasicFunctionalTest.txt, dev/tests/verification/Resources/ExecuteInSeleniumTest.txt, src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
=> 2.6.1 rc to Master

docs/metadata.md
Added a missing operations node in the example.
=> Added missing node

docs/data.md
Example added from the existing test file for grapValueFrom element
=> Example added for grapValueFrom element

docs/getting-started.md
The command from the 'Set up an embedded MFTF -> Step 3' has to be executed from project root.
=> Small fix to the Mftf Getting Started doc

.travis.yml, composer.json, composer.lock
removed support for php7.0/7.1
2. ...
=> MQE-1738: MFTF remove compatilibity with PHP 7.0/7.1

src/Magento/FunctionalTestingFramework/Util/Script/ScriptUtil.php
Updated new file ScriptUtil with LEVEL_DEFAULT
2. ...
=> MQE-1581: Remove NONE debug level for next MFTF major release

src/Magento/FunctionalTestingFramework/Upgrade/UpdateAssertionSchema.php
- Fixed Ugprade script to use new format
=> MQE-683: [Deprecation] Only use more nested assertion syntax

docs/best-practices.md
In my opinion the most important for Best Practices is:
1. Focus on reusability
1. Contribution
I've updated the Best Practices to follow these principles.
Further updated are necessary, but I'm going to provide them soon.
N/A
=> DevDocs: Update Best Practices

docs/configuration.md
As far as I see - documentation was missing information about BACKEND_DOMAIN support.
N/A
=> DevDocs: Add missing information about Backend Domain support.

docs/introduction.md
Explained more in detail - without reference to legacy MTF - what actually is MFTF.
Updated audience and use cases.
N/A
=> DevDocs: Update documentation for Introduction page

docs/versioning.md
Not much to be done there. Update information about version compatibility.
N/A
=> DevDocs: Update documentation regarding Versioning

docs/update.md
Optimized whole instruction for Update process.
Also fixed the link that is not displaying properly: https://devdocs.magento.com/mftf/docs/update.html
N/A
=> DevDocs: Update documentation regarding Update process

docs/best-practices.md
This PR fixes a syntax error that was breaking rendering.
=> Escaped Liquid tag syntax

CHANGELOG.md
=> MQE-2023: CHANGELOG.MD and Composer version bump

src/Magento/FunctionalTestingFramework/StaticCheck/TestDependencyCheck.php, src/Magento/FunctionalTestingFramework/Upgrade/RemoveModuleFileInSuiteFiles.php, src/Magento/FunctionalTestingFramework/Upgrade/RenameMetadataFiles.php, src/Magento/FunctionalTestingFramework/Upgrade/SplitMultipleEntitiesFiles.php, src/Magento/FunctionalTestingFramework/Upgrade/UpdateAssertionSchema.php, src/Magento/FunctionalTestingFramework/Upgrade/UpdateTestSchemaPaths.php, src/Magento/FunctionalTestingFramework/Util/Script/ScriptUtil.php
=> MQE-1980: dependency static test fix and static test refactoring

src/Magento/FunctionalTestingFramework/Console/RunTestFailedCommand.php
=> MQE-2094: Test failure re-run error for extn builds

docs/getting-started.md
I removed an unnecessary code snippet which doesn't make sense where it's.
=> Getting started > Removing code snippet

CHANGELOG.md
=> MQE-2097: CHANGELOG.MD and Composer version bump

.gitignore, docs/commands/mftf.md, src/Magento/FunctionalTestingFramework/StaticCheck/AnnotationsCheck.php, src/Magento/FunctionalTestingFramework/StaticCheck/StaticChecksList.php, src/Magento/FunctionalTestingFramework/Test/Handlers/TestObjectHandler.php, src/Magento/FunctionalTestingFramework/Test/Util/ActionGroupAnnotationExtractor.php, src/Magento/FunctionalTestingFramework/Test/Util/AnnotationExtractor.php, src/Magento/FunctionalTestingFramework/Test/Util/TestObjectExtractor.php
* Add a new static check that validates test annotations
* Run via `bin/mftf static-checks annotations`
=> MQE-942: MFTF Annotation Static Check

etc/config/functional.suite.dist.yml
https://jira.corp.magento.com/browse/MQE-2131
Also required for https://jira.corp.magento.com/browse/MTS-1245
https://github.com/magento-cicd/jenkins-infra/pull/7
=> MQE-2131: Chrome 75+ requires unhandledPromptBehavior driver capability

src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/PersistedObjectHandler.php
=> MQE-2129: Error creating data entity due to decryption error

CHANGELOG.md
=> MQE-2117: CHANGELOG.MD and Composer version bump

CHANGELOG.md, etc/config/functional.suite.dist.yml, src/Magento/FunctionalTestingFramework/DataGenerator/Handlers/PersistedObjectHandler.php, src/Magento/FunctionalTestingFramework/Helper/HelperContainer.php, src/Magento/FunctionalTestingFramework/Helper/views/TestInjectMethod.mustache, src/Magento/FunctionalTestingFramework/ObjectManager/ObjectHandlerInterface.php, src/Magento/FunctionalTestingFramework/StaticCheck/AnnotationsCheck.php, src/Magento/FunctionalTestingFramework/Suite/Generators/GroupClassGenerator.php, src/Magento/FunctionalTestingFramework/Suite/views/SuiteClass.mustache
Merging 3.0.0 RC3 to develop
2. ...
=> 3.0.0 RC3 >> develop

bin/mftf, composer.json, composer.lock
=> Release candidate test

CHANGELOG.md, src/Magento/FunctionalTestingFramework/Module/MagentoActionProxies.php, src/Magento/FunctionalTestingFramework/Module/MagentoWebDriver.php
=> Merge 3.0.0 RC4 back to develop

etc/config/.env.example, etc/config/functional.suite.dist.yml, src/Magento/FunctionalTestingFramework/Suite/views/SuiteClass.mustache, src/Magento/FunctionalTestingFramework/Suite/views/partials/testActions.mustache
=> Chrome hung fix

CHANGELOG.md, composer.json, composer.lock
=> MQE-2153: CHANGELOG.md updated and composer version bumped to 3.0.0-RC4

CHANGELOG.md, composer.json, composer.lock
=> MQE-2180: CHANGELOG.MD and Composer version bump

CHANGELOG.md, composer.json, composer.lock
* MQE-2180: CHANGELOG.MD and Composer version bump
* MQE-2180: CHANGELOG.MD and Composer version bump
2. ...
=> 3.0.0-RC5 >> develop

CHANGELOG.md, composer.json, composer.lock
=> 2.6.5-RC >> 2.x-develop

docs/configure-2fa.md
This PR adds raw tags to the 2fa topic to prevent devdocs build errors.
=> Adding raw tag to topic to prevent build errors

.github/CONTRIBUTING.md, CODE_OF_CONDUCT.md, README.md
=> [develop] MQE-2231: Adobe open source repository standards compliance

README.md
=> MQE-2231: Adobe open source repository standards compliance

README.md
=> [master] MQE-2231: Adobe open source repository standards compliance 

.github/workflows/php.yml
=> MQE-2255: Migrate MFTF builds out of Travis

CHANGELOG.md, composer.json, composer.lock
=> 3.1.1 >> develop

composer.json, composer.lock
1. [MTS-1836](https://jira.corp.magento.com/browse/MTS-1836): Upgrade csharpru/vault-php to 4.1+
=> MTS-1836: Upgrade csharpru/vault-php to 4.1+

docs/configuration.md, etc/config/.env.example, src/Magento/FunctionalTestingFramework/DataTransport/Auth/WebApiAuth.php
=> Add support for admin WebAPI token refresh

docs/introduction.md
=> fix typo in doc

composer.json, composer.lock
This PR provides the update of the `monolog/monolog` to the latest version (2.3.1)
1. magento/magento2#32868
https://github.com/magento/magento2/pull/33497
=> CE-32868: Updated "monolog" to the latest version 2.3.1

docs/configuration.md
Add access/secret key config parameters necessary to configure S3 bucket that requires it.
2. ...
=> Add access/secret key config parameters

dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Persist/OperationDataArrayResolverTest.php
Eliminated AspectMock usage from `dev/tests/unit/Magento/FunctionalTestFramework/DataGenerator/Persist/OperationDataArrayResolverTest.php`
1. Fixes magento/magento2#33296: [MFTF] Eliminate AspectMock from OperationDataArrayResolverTest (Complex!)
=> Issue 33296: Eliminate AspectMock from OperationDataArrayResolverTest

dev/tests/unit/Util/EntityDataObjectBuilder.php, dev/tests/unit/Util/OperationElementBuilder.php, src/Magento/FunctionalTestingFramework/DataGenerator/Persist/OperationDataArrayResolver.php, src/Magento/FunctionalTestingFramework/Util/TestGenerator.php
This PR contain fix to revert back test and test object generation to previous behavior
1. https://jira.corp.magento.com/browse/AC-1193: Fix broken MFTF tests
=> AC-1193: Fix broken MFTF tests
